USE [Production10.2_SSRS]
GO

/****** Object:  Table [dbo].[Company_B2408577EA074F3791D03D37E236EC66]    Script Date: 4/27/2018 4:58:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Company_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[Address1] [nvarchar](max) NULL,
	[Address2] [nvarchar](max) NULL,
	[Address3] [nvarchar](max) NULL,
	[City] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
	[DeepCopy] [bit] NULL,
	[DeepCopyDupOrRevEst] [bit] NULL,
	[FaxNum] [nvarchar](max) NULL,
	[MapURL] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[PhoneNum] [nvarchar](max) NULL,
	[State] [nvarchar](max) NULL,
	[WIApplication] [nvarchar](max) NULL,
	[WIAutoCreateJob] [bit] NULL,
	[WIGetDetails] [bit] NULL,
	[WIRelease] [bit] NULL,
	[WISchedule] [bit] NULL,
	[WIShippingCosts] [bit] NULL,
	[Zip] [nvarchar](max) NULL,
	[Calc_AddressList] [nvarchar](max) NULL,
	[Calc_PrintCompanyName] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[Customer_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[AcctRefNumber] [nvarchar](max) NULL,
	[AcrossNatAcc] [bit] NULL,
	[AddlHdlgFlag] [bit] NULL,
	[Address1] [nvarchar](max) NULL,
	[Address2] [nvarchar](max) NULL,
	[Address3] [nvarchar](max) NULL,
	[AddressVal] [bit] NULL,
	[AEPLOQType] [nvarchar](max) NULL,
	[AGAFIPResponsibilityCode] [nvarchar](max) NULL,
	[AGBillToProvinceCode] [nvarchar](max) NULL,
	[AGGrossIncomeTaxID] [nvarchar](max) NULL,
	[AGIDDocTypeCode] [nvarchar](max) NULL,
	[AGIDDocumentNumber] [nvarchar](max) NULL,
	[AGProvinceCode] [nvarchar](max) NULL,
	[AGUseGoodDefaultMark] [bit] NULL,
	[AllocPriorityCode] [nvarchar](max) NULL,
	[AllowAltBillTo] [bit] NULL,
	[AllowAsAltRemitTo] [bit] NULL,
	[AllowOTS] [bit] NULL,
	[AllowShipTo3] [bit] NULL,
	[ApplyChrg] [bit] NULL,
	[ARInvoiceAdjITCode] [nvarchar](max) NULL,
	[ARInvoiceITCode] [nvarchar](max) NULL,
	[BillDay] [int] NULL,
	[BillFrequency] [nvarchar](max) NULL,
	[BorderCrossing] [nvarchar](max) NULL,
	[BTAddress1] [nvarchar](max) NULL,
	[BTAddress2] [nvarchar](max) NULL,
	[BTAddress3] [nvarchar](max) NULL,
	[BTCity] [nvarchar](max) NULL,
	[BTCountry] [nvarchar](max) NULL,
	[BTCountryNum] [int] NULL,
	[BTFaxNum] [nvarchar](max) NULL,
	[BTFormatStr] [nvarchar](max) NULL,
	[BTName] [nvarchar](max) NULL,
	[BTPhoneNum] [nvarchar](max) NULL,
	[BTState] [nvarchar](max) NULL,
	[BTZip] [nvarchar](max) NULL,
	[BusinessCust] [nvarchar](max) NULL,
	[CertOfOrigin] [bit] NULL,
	[ChangeDate] [date] NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [int] NULL,
	[ChargeCode] [nvarchar](max) NULL,
	[CheckConfirmCapPromise] [bit] NULL,
	[CheckDateCapPromise] [bit] NULL,
	[CheckDuplicatePO] [bit] NULL,
	[CheckUpdateCapPromise] [bit] NULL,
	[ChrgAmount] [decimal](17, 3) NULL,
	[City] [nvarchar](max) NULL,
	[COD] [bit] NULL,
	[CODAmount] [decimal](17, 3) NULL,
	[CODCheck] [bit] NULL,
	[CODFreight] [bit] NULL,
	[Comment] [nvarchar](max) NULL,
	[CommercialInvoice] [bit] NULL,
	[Company] [nvarchar](max) NULL,
	[ConsolidateSO] [bit] NULL,
	[ContBillDay] [int] NULL,
	[Country] [nvarchar](max) NULL,
	[CountryNum] [int] NULL,
	[CreditCardOrder] [bit] NULL,
	[CreditClearDate] [date] NULL,
	[CreditClearTime] [nvarchar](max) NULL,
	[CreditClearUserID] [nvarchar](max) NULL,
	[CreditHold] [bit] NULL,
	[CreditHoldDate] [date] NULL,
	[CreditHoldSource] [nvarchar](max) NULL,
	[CreditIncludeOrders] [bit] NULL,
	[CreditIncludePI] [bit] NULL,
	[CreditLimit] [decimal](15, 0) NULL,
	[CreditMemoITCode] [nvarchar](max) NULL,
	[CreditReviewDate] [date] NULL,
	[CSR] [nvarchar](max) NULL,
	[CurrencyCode] [nvarchar](max) NULL,
	[CustID] [nvarchar](max) NULL,
	[CustNum] [int] NULL,
	[CustomerType] [nvarchar](max) NULL,
	[CustPartOpts] [nvarchar](max) NULL,
	[CustPILimit] [decimal](15, 0) NULL,
	[CustPricingSchema] [nvarchar](max) NULL,
	[CustURL] [nvarchar](max) NULL,
	[DeclaredAmt] [decimal](17, 3) NULL,
	[DeclaredIns] [bit] NULL,
	[DefaultFOB] [nvarchar](max) NULL,
	[DefaultInvoicestyle] [nvarchar](max) NULL,
	[DefaultLOQstyle] [nvarchar](max) NULL,
	[DefaultOrderAcknowledgement] [nvarchar](max) NULL,
	[DefaultOversPricing] [nvarchar](max) NULL,
	[DefaultPackSlip] [nvarchar](max) NULL,
	[DeferredRev] [bit] NULL,
	[DeliveryConf] [int] NULL,
	[DeliveryType] [nvarchar](max) NULL,
	[DemandAddAction] [nvarchar](max) NULL,
	[DemandAddLeadTime] [int] NULL,
	[DemandCancelAction] [nvarchar](max) NULL,
	[DemandCancelLeadTime] [int] NULL,
	[DemandCapPromiseAction] [nvarchar](max) NULL,
	[DemandCapPromiseDate] [nvarchar](max) NULL,
	[DemandCapPromiseUpdate] [nvarchar](max) NULL,
	[DemandChangeAction] [nvarchar](max) NULL,
	[DemandChangeDateAction] [nvarchar](max) NULL,
	[DemandChangeDateLeadTime] [int] NULL,
	[DemandChangeLeadTime] [int] NULL,
	[DemandCheckCfgAction] [nvarchar](max) NULL,
	[DemandCheckConfig] [bit] NULL,
	[DemandCheckCUMM] [bit] NULL,
	[DemandCheckCUMMAction] [nvarchar](max) NULL,
	[DemandCheckForPart] [bit] NULL,
	[DemandCheckForPartAction] [nvarchar](max) NULL,
	[DemandCheckForRev] [bit] NULL,
	[DemandCheckForRevAction] [nvarchar](max) NULL,
	[DemandCloseNoMatch] [bit] NULL,
	[DemandCloseRejSkd] [bit] NULL,
	[DemandDateType] [nvarchar](max) NULL,
	[DemandDeliveryDays] [int] NULL,
	[DemandNewLineAction] [nvarchar](max) NULL,
	[DemandNewLineLeadTime] [int] NULL,
	[DemandPricing] [nvarchar](max) NULL,
	[DemandQtyChangeAction] [nvarchar](max) NULL,
	[DemandQtyChangeLeadTime] [int] NULL,
	[DemandSplitSched] [bit] NULL,
	[DemandUnitPriceDiff] [bit] NULL,
	[DemandUnitPriceDiffAction] [nvarchar](max) NULL,
	[DirectDebiting] [bit] NULL,
	[DiscountPercent] [decimal](6, 2) NULL,
	[DiscountQualifier] [nvarchar](max) NULL,
	[DmdCheckPartialShip] [bit] NULL,
	[DmdCheckShipAction] [nvarchar](max) NULL,
	[DocGlobalCreditLimit] [decimal](15, 0) NULL,
	[DocGlobalPILimit] [decimal](15, 0) NULL,
	[DocOnly] [bit] NULL,
	[DueDateCriteria] [nvarchar](max) NULL,
	[EarlyBuffer] [int] NULL,
	[EDICode] [nvarchar](max) NULL,
	[EMailAddress] [nvarchar](max) NULL,
	[ERSOrder] [bit] NULL,
	[EstDate] [date] NULL,
	[ETCAddrChg] [bit] NULL,
	[ExcFromVal] [bit] NULL,
	[ExternalDeliveryNote] [bit] NULL,
	[ExternalID] [nvarchar](max) NULL,
	[ExtID] [nvarchar](max) NULL,
	[FaxNum] [nvarchar](max) NULL,
	[FederalID] [nvarchar](max) NULL,
	[FFAddress1] [nvarchar](max) NULL,
	[FFAddress2] [nvarchar](max) NULL,
	[FFAddress3] [nvarchar](max) NULL,
	[FFCity] [nvarchar](max) NULL,
	[FFCompName] [nvarchar](max) NULL,
	[FFContact] [nvarchar](max) NULL,
	[FFCountry] [nvarchar](max) NULL,
	[FFCountryNum] [int] NULL,
	[FFID] [nvarchar](max) NULL,
	[FFPhoneNum] [nvarchar](max) NULL,
	[FFState] [nvarchar](max) NULL,
	[FFZip] [nvarchar](max) NULL,
	[FinCharges] [bit] NULL,
	[FormatStr] [nvarchar](max) NULL,
	[GlbNACreditIsShare] [bit] NULL,
	[GlbNACreditSharedPrc] [decimal](7, 2) NULL,
	[GlbNAParentCreditIsUsed] [bit] NULL,
	[GlbNAParentCreditPrc] [decimal](7, 2) NULL,
	[GlobalCredIncOrd] [bit] NULL,
	[GlobalCredIncPI] [bit] NULL,
	[GlobalCreditHold] [nvarchar](max) NULL,
	[GlobalCreditLimit] [decimal](15, 0) NULL,
	[GlobalCurrencyCode] [nvarchar](max) NULL,
	[GlobalCust] [bit] NULL,
	[GlobalLock] [bit] NULL,
	[GlobalPILimit] [decimal](15, 0) NULL,
	[GroundType] [nvarchar](max) NULL,
	[GroupCode] [nvarchar](max) NULL,
	[HasBank] [bit] NULL,
	[Hazmat] [bit] NULL,
	[ICCust] [bit] NULL,
	[ICTrader] [bit] NULL,
	[IndividualPackIDs] [bit] NULL,
	[IntrntlShip] [bit] NULL,
	[InvPerPackLine] [bit] NULL,
	[LangNameID] [nvarchar](max) NULL,
	[LateBuffer] [int] NULL,
	[LegalName] [nvarchar](max) NULL,
	[LetterOfInstr] [bit] NULL,
	[LinkPortNum] [int] NULL,
	[LOQBookCaFinishing] [bit] NULL,
	[LOQBookCapaper] [bit] NULL,
	[LOQBookCaPress] [bit] NULL,
	[LOQBookCatPlates] [bit] NULL,
	[LOQBookPCFinishing] [bit] NULL,
	[LOQBookPCPaper] [bit] NULL,
	[LOQBookPCPlates] [bit] NULL,
	[LOQBookPCPress] [bit] NULL,
	[LOQPrepressStyle] [nvarchar](max) NULL,
	[LOQVariations] [bit] NULL,
	[ManagedVendID] [nvarchar](max) NULL,
	[ManagedVendNum] [int] NULL,
	[MarkUpID] [nvarchar](max) NULL,
	[MiscCashRecITCode] [nvarchar](max) NULL,
	[NACreditIsShare] [bit] NULL,
	[NACreditPreferenceList] [nvarchar](max) NULL,
	[NACreditSharedPrc] [decimal](7, 2) NULL,
	[Name] [nvarchar](max) NULL,
	[NAParentCreditIsUsed] [bit] NULL,
	[NAParentCreditPrc] [decimal](7, 2) NULL,
	[NARlsClassCode] [nvarchar](max) NULL,
	[NoContact] [bit] NULL,
	[NonStdPkg] [bit] NULL,
	[NotifyEMail] [nvarchar](max) NULL,
	[NotifyFlag] [bit] NULL,
	[OneInvPerPS] [bit] NULL,
	[OrderHoldForReview] [bit] NULL,
	[OrgRegCode] [nvarchar](max) NULL,
	[OTSmartString] [bit] NULL,
	[OTSSaveAs] [nvarchar](max) NULL,
	[OurBankCode] [nvarchar](max) NULL,
	[OverrideRlsClass] [bit] NULL,
	[OversPct] [decimal](14, 5) NULL,
	[ParamCode] [nvarchar](max) NULL,
	[ParentCustNum] [int] NULL,
	[PBTerms] [int] NULL,
	[PendingTerritoryID] [nvarchar](max) NULL,
	[PeriodicBilling] [bit] NULL,
	[PeriodicityCode] [int] NULL,
	[PhoneNum] [nvarchar](max) NULL,
	[PMUID] [int] NULL,
	[PreferredBank] [nvarchar](max) NULL,
	[PriceTolerance] [decimal](17, 5) NULL,
	[PrimBCon] [int] NULL,
	[PrimPCon] [int] NULL,
	[PrimSCon] [int] NULL,
	[PrintAck] [bit] NULL,
	[PrintLabels] [bit] NULL,
	[PrintStatements] [bit] NULL,
	[RACode] [nvarchar](max) NULL,
	[RebateForm] [nvarchar](max) NULL,
	[RebateVendorNum] [int] NULL,
	[RefNotes] [nvarchar](max) NULL,
	[ReminderCode] [nvarchar](max) NULL,
	[ResaleID] [nvarchar](max) NULL,
	[ResDelivery] [bit] NULL,
	[ReservePriorityCode] [nvarchar](max) NULL,
	[RfqAttachAllow] [bit] NULL,
	[SalesRepCode] [nvarchar](max) NULL,
	[SatDelivery] [bit] NULL,
	[SatPickup] [bit] NULL,
	[ServAlert] [bit] NULL,
	[ServAuthNum] [nvarchar](max) NULL,
	[ServDeliveryDate] [date] NULL,
	[ServHomeDel] [bit] NULL,
	[ServInstruct] [nvarchar](max) NULL,
	[ServPhone] [nvarchar](max) NULL,
	[ServRef1] [nvarchar](max) NULL,
	[ServRef2] [nvarchar](max) NULL,
	[ServRef3] [nvarchar](max) NULL,
	[ServRef4] [nvarchar](max) NULL,
	[ServRef5] [nvarchar](max) NULL,
	[ServRelease] [bit] NULL,
	[ServSignature] [bit] NULL,
	[ShipExprtDeclartn] [bit] NULL,
	[ShippingQualifier] [nvarchar](max) NULL,
	[ShipToNum] [nvarchar](max) NULL,
	[ShipToTerrList] [nvarchar](max) NULL,
	[ShipViaCode] [nvarchar](max) NULL,
	[State] [nvarchar](max) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[TaxAuthorityCode] [nvarchar](max) NULL,
	[TaxExempt] [nvarchar](max) NULL,
	[TaxMethod] [nvarchar](max) NULL,
	[TaxRegionCode] [nvarchar](max) NULL,
	[TaxRegReason] [nvarchar](max) NULL,
	[TaxRoundRule] [int] NULL,
	[TermsCode] [nvarchar](max) NULL,
	[TerritoryID] [nvarchar](max) NULL,
	[TerritoryLock] [bit] NULL,
	[THBranchID] [nvarchar](max) NULL,
	[ThirdPLCust] [bit] NULL,
	[TradingPartnerName] [nvarchar](max) NULL,
	[UndersPct] [decimal](14, 5) NULL,
	[UPSQuantumView] [bit] NULL,
	[UPSQVEmailType] [nvarchar](max) NULL,
	[UPSQVMemo] [nvarchar](max) NULL,
	[UPSQVShipFromName] [nvarchar](max) NULL,
	[ValidPayer] [bit] NULL,
	[ValidShipTo] [bit] NULL,
	[ValidSoldTo] [bit] NULL,
	[Variations] [bit] NULL,
	[WebCustomer] [bit] NULL,
	[WIApplication] [nvarchar](max) NULL,
	[WICustomer] [nvarchar](max) NULL,
	[WIShippingCosts] [bit] NULL,
	[Zip] [nvarchar](max) NULL,
	[CofC_c] [bit] NULL,
	[SCRep_c] [nvarchar](max) NULL,
	[Industry_c] [nvarchar](max) NULL,
	[PickComments_c] [nvarchar](max) NULL,
	[Combine_c] [nvarchar](max) NULL,
	[APM_Email_c] [nvarchar](max) NULL,
	[APM_Email2_c] [nvarchar](max) NULL,
	[APM_Email3_c] [nvarchar](max) NULL,
	[MktCampaignID_c] [nvarchar](max) NULL,
	[MktgEvntSeq_c] [int] NULL,
	[Notification_c] [bit] NULL,
	[NotifyConfirm_c] [bit] NULL,
	[MS_c] [bit] NULL,
	[OtherEvent_c] [nvarchar](max) NULL,
	[InvAgreeExpire_c] [date] NULL,
	[InvAgreement_c] [bit] NULL,
	[MgmtOver_c] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[CustomerDocs_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[AcceptType] [nvarchar](max) NULL,
	[AltTradingPartnerName] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[CustNum] [int] NULL,
	[DocDirection] [nvarchar](max) NULL,
	[DocumentName] [nvarchar](max) NULL,
	[DocumentType] [nvarchar](max) NULL,
	[EDIPartValidation] [nvarchar](max) NULL,
	[MapID] [nvarchar](max) NULL,
	[OutboundAutomatic] [bit] NULL,
	[OutboundDocName] [nvarchar](max) NULL,
	[OutBoundDocReq] [bit] NULL,
	[OutboundManual] [bit] NULL,
	[ShipToNum] [nvarchar](max) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[Calc_OrderNum] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[FSContDt_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[BillEndDate] [date] NULL,
	[BillStartDate] [date] NULL,
	[ChangeDate] [date] NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [int] NULL,
	[Company] [nvarchar](max) NULL,
	[ContractLine] [int] NULL,
	[ContractNum] [int] NULL,
	[ContractQty] [decimal](22, 8) NULL,
	[DateInactivated] [date] NULL,
	[DateInvoiced] [date] NULL,
	[DocPricePerUnit] [decimal](17, 5) NULL,
	[Inactive] [bit] NULL,
	[Invoiced] [bit] NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[PartNum] [nvarchar](max) NULL,
	[Rpt1PricePerUnit] [decimal](17, 5) NULL,
	[Rpt2PricePerUnit] [decimal](17, 5) NULL,
	[Rpt3PricePerUnit] [decimal](17, 5) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[Calc_OrderLine] [int] NULL,
	[Calc_OrderNum] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[JobProd_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[CallLine] [int] NULL,
	[CallNum] [int] NULL,
	[Company] [nvarchar](max) NULL,
	[DemandContractNum] [int] NULL,
	[DemandDtlSeq] [int] NULL,
	[DemandHeadSeq] [int] NULL,
	[DemandScheduleSeq] [int] NULL,
	[JobNum] [nvarchar](max) NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[OrderRelNum] [int] NULL,
	[PartNum] [nvarchar](max) NULL,
	[PlanID] [nvarchar](max) NULL,
	[Plant] [nvarchar](max) NULL,
	[PlanUserID] [nvarchar](max) NULL,
	[ProdQty] [decimal](22, 8) NULL,
	[ReceivedQty] [decimal](22, 8) NULL,
	[ShippedQty] [decimal](22, 8) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[TargetAssemblySeq] [int] NULL,
	[TargetJobNum] [nvarchar](max) NULL,
	[TargetMtlSeq] [int] NULL,
	[TFLineNum] [nvarchar](max) NULL,
	[WarehouseCode] [nvarchar](max) NULL,
	[WIPQty] [decimal](22, 8) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OHOrderMsc_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[ChangeTrackAmount] [decimal](14, 5) NULL,
	[ChangeTrackApproved] [bit] NULL,
	[ChangeTrackMemoDesc] [nvarchar](max) NULL,
	[ChangeTrackMemoText] [nvarchar](max) NULL,
	[ChangeTrackStatus] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[DocMiscAmt] [decimal](17, 3) NULL,
	[FreqCode] [nvarchar](max) NULL,
	[MiscCode] [nvarchar](max) NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[SeqNum] [int] NULL,
	[Calc_ChargeDesc] [nvarchar](max) NULL,
	[Calc_SalesAnalysis] [bit] NULL,
	[OrderNum_CardMemberName] [nvarchar](max) NULL,
	[OrderNum_CurrencyCode] [nvarchar](max) NULL,
	[OrderNum_CheckBox01_c] [bit] NULL,
	[OrderNum_FreightTerms_c] [nvarchar](max) NULL,
	[OrderNum_ThirdParty_c] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OrderDtl_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[ChangeDate] [date] NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [int] NULL,
	[Company] [nvarchar](max) NULL,
	[ContractNum] [int] NULL,
	[CustNum] [int] NULL,
	[DefaultOversPricing] [nvarchar](max) NULL,
	[DemandContractLine] [int] NULL,
	[DemandContractNum] [int] NULL,
	[DemandDtlSeq] [int] NULL,
	[DemandHeadSeq] [int] NULL,
	[DiscBreakListCode] [nvarchar](max) NULL,
	[DiscListPrice] [decimal](17, 5) NULL,
	[DisplaySeq] [decimal](9, 3) NULL,
	[DocDiscount] [decimal](17, 3) NULL,
	[DocExtPriceDtl] [decimal](17, 3) NULL,
	[DocInDiscount] [decimal](17, 3) NULL,
	[DocInExtPriceDtl] [decimal](17, 3) NULL,
	[DocInListPrice] [decimal](17, 5) NULL,
	[DocInOrdBasedPrice] [decimal](17, 5) NULL,
	[DocInUnitPrice] [decimal](17, 5) NULL,
	[DocUnitPrice] [decimal](17, 5) NULL,
	[DoNotShipAfterDate] [date] NULL,
	[DoNotShipBeforeDate] [date] NULL,
	[DupOnJobCrt] [bit] NULL,
	[ECCOrderLine] [int] NULL,
	[ECCOrderNum] [nvarchar](max) NULL,
	[ECCPlant] [nvarchar](max) NULL,
	[ECCQuoteLine] [int] NULL,
	[ECCQuoteNum] [nvarchar](max) NULL,
	[ExtPriceDtl] [decimal](17, 3) NULL,
	[GroupSeq] [int] NULL,
	[InDiscount] [decimal](17, 3) NULL,
	[InExtPriceDtl] [decimal](17, 3) NULL,
	[InListPrice] [decimal](17, 5) NULL,
	[InOrdBasedPrice] [decimal](17, 5) NULL,
	[InUnitPrice] [decimal](17, 5) NULL,
	[KitCompOrigPart] [nvarchar](max) NULL,
	[KitCompOrigSeq] [int] NULL,
	[KitFlag] [nvarchar](max) NULL,
	[KitParentLine] [int] NULL,
	[KitPricing] [nvarchar](max) NULL,
	[KitPrintCompsInv] [bit] NULL,
	[KitPrintCompsPS] [bit] NULL,
	[KitQtyPer] [decimal](18, 8) NULL,
	[KitShipComplete] [bit] NULL,
	[LineStatus] [nvarchar](max) NULL,
	[LockDisc] [bit] NULL,
	[MOMsourceEst] [nvarchar](max) NULL,
	[MOMsourceType] [nvarchar](max) NULL,
	[OldOpenValue] [decimal](16, 2) NULL,
	[OldOurOpenQty] [decimal](16, 2) NULL,
	[OldProdCode] [nvarchar](max) NULL,
	[OldSellingOpenQty] [decimal](16, 2) NULL,
	[OpenLine] [bit] NULL,
	[OrderComment] [nvarchar](max) NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[OrderQty] [decimal](22, 8) NULL,
	[OverrideDiscPriceList] [bit] NULL,
	[Overs] [decimal](14, 5) NULL,
	[OversUnitPrice] [decimal](14, 5) NULL,
	[PartNum] [nvarchar](max) NULL,
	[PlanGUID] [nvarchar](max) NULL,
	[PlanUserID] [nvarchar](max) NULL,
	[POLine] [nvarchar](max) NULL,
	[PrevPartNum] [nvarchar](max) NULL,
	[PrevSellQty] [decimal](12, 2) NULL,
	[PrevXPartNum] [nvarchar](max) NULL,
	[PricePerCode] [nvarchar](max) NULL,
	[Reference] [nvarchar](max) NULL,
	[RenewalNbr] [int] NULL,
	[ReverseCharge] [bit] NULL,
	[RevisionNum] [nvarchar](max) NULL,
	[Rpt1AdvanceBillBal] [decimal](19, 5) NULL,
	[Rpt1Discount] [decimal](19, 5) NULL,
	[Rpt1ExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt1InDiscount] [decimal](19, 5) NULL,
	[Rpt1InExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt1InListPrice] [decimal](17, 5) NULL,
	[Rpt1InOrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt1InUnitPrice] [decimal](17, 5) NULL,
	[Rpt1ListPrice] [decimal](17, 5) NULL,
	[Rpt1OrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt1UnitPrice] [decimal](17, 5) NULL,
	[Rpt2AdvanceBillBal] [decimal](19, 5) NULL,
	[Rpt2Discount] [decimal](19, 5) NULL,
	[Rpt2ExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt2InDiscount] [decimal](19, 5) NULL,
	[Rpt2InExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt2InListPrice] [decimal](17, 5) NULL,
	[Rpt2InOrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt2InUnitPrice] [decimal](17, 5) NULL,
	[Rpt2ListPrice] [decimal](17, 5) NULL,
	[Rpt2OrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt2UnitPrice] [decimal](17, 5) NULL,
	[Rpt3AdvanceBillBal] [decimal](19, 5) NULL,
	[Rpt3Discount] [decimal](19, 5) NULL,
	[Rpt3ExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt3InDiscount] [decimal](19, 5) NULL,
	[Rpt3InExtPriceDtl] [decimal](17, 3) NULL,
	[Rpt3InListPrice] [decimal](17, 5) NULL,
	[Rpt3InOrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt3InUnitPrice] [decimal](17, 5) NULL,
	[Rpt3ListPrice] [decimal](17, 5) NULL,
	[Rpt3OrdBasedPrice] [decimal](17, 5) NULL,
	[Rpt3UnitPrice] [decimal](17, 5) NULL,
	[SalesUM] [nvarchar](max) NULL,
	[SellingFactorDirection] [nvarchar](max) NULL,
	[SellingQuantity] [decimal](22, 8) NULL,
	[SmartString] [nvarchar](max) NULL,
	[SmartStringProcessed] [bit] NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[TotalReleases] [int] NULL,
	[Unders] [decimal](14, 5) NULL,
	[UndersPct] [decimal](14, 5) NULL,
	[UnitPrice] [decimal](17, 5) NULL,
	[Warranty] [bit] NULL,
	[WarrantyCode] [nvarchar](max) NULL,
	[WarrantyComment] [nvarchar](max) NULL,
	[XPartNum] [nvarchar](max) NULL,
	[XRevisionNum] [nvarchar](max) NULL,
	[OnHold_c] [bit] NULL,
	[PriceLock_c] [bit] NULL,
	[Calc_Duration] [nvarchar](max) NULL,
	[Calc_ExtPrice] [decimal](38, 9) NULL,
	[Calc_LabDur] [nvarchar](max) NULL,
	[Calc_LabMod] [nvarchar](max) NULL,
	[Calc_Labor] [nvarchar](max) NULL,
	[Calc_LineDesc] [nvarchar](max) NULL,
	[Calc_MatDur] [nvarchar](max) NULL,
	[Calc_Mate] [nvarchar](max) NULL,
	[Calc_MatMod] [nvarchar](max) NULL,
	[Calc_Misc] [nvarchar](max) NULL,
	[Calc_MiscDur] [nvarchar](max) NULL,
	[Calc_MiscMod] [nvarchar](max) NULL,
	[Calc_Modifier] [nvarchar](max) NULL,
	[Calc_POLine] [nvarchar](max) NULL,
	[Calc_PrevPartNum] [nvarchar](max) NULL,
	[Calc_PrevSellQty] [nvarchar](max) NULL,
	[Calc_PrevXPartNum] [nvarchar](max) NULL,
	[Calc_RepRate] [decimal](38, 9) NULL,
	[Calc_SalesPerson] [nvarchar](max) NULL,
	[Calc_UOMForeignDesc] [nvarchar](max) NULL,
	[Calc_WarrComment] [nvarchar](max) NULL,
	[Calc_WarrDesc] [nvarchar](max) NULL,
	[ContractCode_ContractDescription] [nvarchar](max) NULL,
	[MktgCampaignID_CampDescription] [nvarchar](max) NULL,
	[MktgEvnt_EvntDescription] [nvarchar](max) NULL,
	[MktgEvnt_Other_c] [bit] NULL,
	[OrderNum_CardMemberName] [nvarchar](max) NULL,
	[OrderNum_CurrencyCode] [nvarchar](max) NULL,
	[OrderNum_CheckBox01_c] [bit] NULL,
	[OrderNum_FreightTerms_c] [nvarchar](max) NULL,
	[OrderNum_ThirdParty_c] [nvarchar](max) NULL,
	[PartNum_MfgComment] [nvarchar](max) NULL,
	[PartNum_PartDescription] [nvarchar](max) NULL,
	[PartNum_PurComment] [nvarchar](max) NULL,
	[PartNum_TrackDimension] [bit] NULL,
	[PartNum_TrackLots] [bit] NULL,
	[PartNum_TrackSerialNum] [bit] NULL,
	[PartNum_Bare_c] [nvarchar](max) NULL,
	[PartNum_CartonWeight_c] [decimal](38, 9) NULL,
	[PartNum_CartperPallet_c] [decimal](38, 9) NULL,
	[PartNum_Commission_c] [nvarchar](max) NULL,
	[PartNum_CommissionExpire_c] [datetime] NULL,
	[PartNum_CreateUser_c] [nvarchar](max) NULL,
	[PartNum_DrawingNumber_c] [nvarchar](max) NULL,
	[PartNum_Excess_c] [bit] NULL,
	[PartNum_ExpireDate_c] [datetime] NULL,
	[PartNum_FreightClass_c] [nvarchar](max) NULL,
	[PartNum_Inspect_c] [bit] NULL,
	[PartNum_InventoryAgreement_c] [bit] NULL,
	[PartNum_Lifo_c] [decimal](38, 9) NULL,
	[PartNum_ManageApprove_c] [bit] NULL,
	[PartNum_MplsSS_c] [decimal](38, 9) NULL,
	[PartNum_NMFC_Code_c] [nvarchar](max) NULL,
	[PartNum_OpenStock_c] [bit] NULL,
	[PartNum_Pack_c] [decimal](38, 9) NULL,
	[PartNum_PcsPerPallet_c] [int] NULL,
	[PartNum_PrimaryComponent_c] [bit] NULL,
	[PartNum_VendItem_c] [nvarchar](max) NULL,
	[ProdCode_Description] [nvarchar](max) NULL,
	[ProjectID_Description] [nvarchar](max) NULL,
	[QuoteNum_CurrencyCode] [nvarchar](max) NULL,
	[QuoteNum_Acknowledged_c] [bit] NULL,
	[QuoteNum_ActiveTeam_c] [nvarchar](max) NULL,
	[QuoteNum_Contact_c] [nvarchar](max) NULL,
	[QuoteNum_Decision_c] [nvarchar](max) NULL,
	[QuoteNum_DecisionDate_c] [datetime] NULL,
	[QuoteNum_DecisionNotes_c] [nvarchar](max) NULL,
	[QuoteNum_EstAnnualVolume_c] [decimal](38, 9) NULL,
	[QuoteNum_EstGPDol_c] [decimal](38, 9) NULL,
	[QuoteNum_EstGPPer_c] [decimal](38, 9) NULL,
	[QuoteNum_EstRevenue_c] [decimal](38, 9) NULL,
	[QuoteNum_ForToPM_c] [bit] NULL,
	[QuoteNum_ForToPMDate_c] [datetime] NULL,
	[QuoteNum_LossReason_c] [nvarchar](max) NULL,
	[QuoteNum_OldOppNum_c] [int] NULL,
	[QuoteNum_OldQuote_c] [bit] NULL,
	[QuoteNum_OldQuoteNum_c] [int] NULL,
	[QuoteNum_PM_c] [nvarchar](max) NULL,
	[QuoteNum_PMComments_c] [nvarchar](max) NULL,
	[QuoteNum_Priority_c] [nvarchar](max) NULL,
	[QuoteNum_Prob_c] [int] NULL,
	[QuoteNum_ProjectName_c] [nvarchar](max) NULL,
	[QuoteNum_Sales_c] [bit] NULL,
	[QuoteNum_SCQuote_c] [bit] NULL,
	[QuoteNum_SendtoCustomer_c] [bit] NULL,
	[QuoteNum_SenttoCustDate_c] [datetime] NULL,
	[QuoteNum_Status_c] [nvarchar](max) NULL,
	[QuoteNum_SubToPM_c] [bit] NULL,
	[QuoteNum_SubToPMDate_c] [datetime] NULL,
	[QuoteNum_Topic_c] [nvarchar](max) NULL,
	[SalesCatID_Description] [nvarchar](max) NULL,
	[SalesUM_UOMSymbol] [nvarchar](max) NULL,
	[TaxCatID_Description] [nvarchar](max) NULL,
	[WarrantyCode_WarrDescription] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OrderHed_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[CardNumber] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[CustNum] [int] NULL,
	[DocTotalDiscount] [decimal](17, 3) NULL,
	[DocTotalMisc] [decimal](17, 3) NULL,
	[DocTotalTax] [decimal](17, 3) NULL,
	[ECCOrderNum] [nvarchar](max) NULL,
	[ECCPaymentMethod] [nvarchar](max) NULL,
	[ECCPONum] [nvarchar](max) NULL,
	[FOB] [nvarchar](max) NULL,
	[IsCSRSet] [bit] NULL,
	[NeedByDate] [date] NULL,
	[OrderComment] [nvarchar](max) NULL,
	[OrderCSR] [nvarchar](max) NULL,
	[OrderDate] [date] NULL,
	[OrderNum] [int] NULL,
	[PONum] [nvarchar](max) NULL,
	[TotalMisc] [decimal](17, 3) NULL,
	[TotalTax] [decimal](17, 3) NULL,
	[TotalWHTax] [decimal](17, 3) NULL,
	[WIApplication] [nvarchar](max) NULL,
	[WICreditCardorder] [bit] NULL,
	[WIOrder] [nvarchar](max) NULL,
	[WIUserID] [nvarchar](max) NULL,
	[WIUsername] [nvarchar](max) NULL,
	[FreightTerms_c] [nvarchar](max) NULL,
	[ThirdParty_c] [nvarchar](max) NULL,
	[CheckBox01_c] [bit] NULL,
	[Calc_BillToAddressList] [nvarchar](max) NULL,
	[Calc_BillToContact] [nvarchar](max) NULL,
	[Calc_BTAddressList] [nvarchar](max) NULL,
	[Calc_CardNumber] [nvarchar](max) NULL,
	[Calc_CarrierDesc] [nvarchar](max) NULL,
	[Calc_CarrierSCAC] [nvarchar](max) NULL,
	[Calc_CustAddrList] [nvarchar](max) NULL,
	[Calc_CustPartOpts] [nvarchar](max) NULL,
	[Calc_FobDesc] [nvarchar](max) NULL,
	[Calc_MiscTotal] [decimal](38, 9) NULL,
	[Calc_MultiNeedDate] [bit] NULL,
	[Calc_MultiRef] [bit] NULL,
	[Calc_MultiRel] [bit] NULL,
	[Calc_MultiShipContacts] [bit] NULL,
	[Calc_MultiShipTo] [bit] NULL,
	[Calc_MultiShipVia] [bit] NULL,
	[Calc_OrderTotal] [decimal](38, 9) NULL,
	[Calc_PrcEmail] [nvarchar](max) NULL,
	[Calc_PrcFax] [nvarchar](max) NULL,
	[Calc_PrcPhone] [nvarchar](max) NULL,
	[Calc_RepRate] [decimal](38, 9) NULL,
	[Calc_SalesPerson] [nvarchar](max) NULL,
	[Calc_ShipToAddressList] [nvarchar](max) NULL,
	[Calc_ShipToContact] [nvarchar](max) NULL,
	[Calc_ShipToEmail] [nvarchar](max) NULL,
	[Calc_ShipToFax] [nvarchar](max) NULL,
	[Calc_ShipToPhone] [nvarchar](max) NULL,
	[Calc_ShipViaDesc] [nvarchar](max) NULL,
	[Calc_SoldToBillToSameFlag] [bit] NULL,
	[Calc_SubTotal] [decimal](38, 9) NULL,
	[Calc_TermsDesc] [nvarchar](max) NULL,
	[CardType_Description] [nvarchar](max) NULL,
	[CurrencyCode_CurrDesc] [nvarchar](max) NULL,
	[CurrencyCode_CurrName] [nvarchar](max) NULL,
	[CurrencyCode_CurrSymbol] [nvarchar](max) NULL,
	[CurrencyCode_DocumentDesc] [nvarchar](max) NULL,
	[Customer_BTName] [nvarchar](max) NULL,
	[Customer_CustID] [nvarchar](max) NULL,
	[Customer_EMailAddress] [nvarchar](max) NULL,
	[Customer_Name] [nvarchar](max) NULL,
	[Customer_ResaleID] [nvarchar](max) NULL,
	[Customer_APM_Email_c] [nvarchar](max) NULL,
	[Customer_APM_Email2_c] [nvarchar](max) NULL,
	[Customer_APM_Email3_c] [nvarchar](max) NULL,
	[Customer_CofC_c] [bit] NULL,
	[Customer_Combine_c] [nvarchar](max) NULL,
	[Customer_Industry_c] [nvarchar](max) NULL,
	[Customer_InvAgreeExpire_c] [datetime] NULL,
	[Customer_InvAgreement_c] [bit] NULL,
	[Customer_MgmtOver_c] [bit] NULL,
	[Customer_MktCampaignID_c] [nvarchar](max) NULL,
	[Customer_MktgEvntSeq_c] [int] NULL,
	[Customer_MS_c] [bit] NULL,
	[Customer_Notification_c] [bit] NULL,
	[Customer_NotifyConfirm_c] [bit] NULL,
	[Customer_OtherEvent_c] [nvarchar](max) NULL,
	[Customer_PickComments_c] [nvarchar](max) NULL,
	[Customer_SCRep_c] [nvarchar](max) NULL,
	[FOB_Description] [nvarchar](max) NULL,
	[ShipViaCode_Description] [nvarchar](max) NULL,
	[ShipViaCode_WebDesc] [nvarchar](max) NULL,
	[ShipViaCode_ServiceCode_c] [nvarchar](max) NULL,
	[TermsCode_Description] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OrderMsc_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[ChangeDate] [date] NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [int] NULL,
	[ChangeTrackAmount] [decimal](14, 5) NULL,
	[ChangeTrackApproved] [bit] NULL,
	[ChangeTrackMemoDesc] [nvarchar](max) NULL,
	[ChangeTrackMemoText] [nvarchar](max) NULL,
	[ChangeTrackStatus] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[DocInMiscAmt] [decimal](17, 3) NULL,
	[DocMiscAmt] [decimal](17, 3) NULL,
	[ExtCompany] [nvarchar](max) NULL,
	[FreqCode] [nvarchar](max) NULL,
	[InMiscAmt] [decimal](17, 3) NULL,
	[MiscAmt] [decimal](17, 3) NULL,
	[MiscCode] [nvarchar](max) NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[Percentage] [decimal](7, 2) NULL,
	[Rpt1InMiscAmt] [decimal](17, 3) NULL,
	[Rpt1MiscAmt] [decimal](17, 3) NULL,
	[Rpt2InMiscAmt] [decimal](17, 3) NULL,
	[Rpt2MiscAmt] [decimal](17, 3) NULL,
	[Rpt3InMiscAmt] [decimal](17, 3) NULL,
	[Rpt3MiscAmt] [decimal](17, 3) NULL,
	[SeqNum] [int] NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[Type] [nvarchar](max) NULL,
	[Calc_ChargeDesc] [nvarchar](max) NULL,
	[Calc_SalesAnalysis] [bit] NULL,
	[MiscCode_Description] [nvarchar](max) NULL,
	[OrderNum_CardMemberName] [nvarchar](max) NULL,
	[OrderNum_CurrencyCode] [nvarchar](max) NULL,
	[OrderNum_CheckBox01_c] [bit] NULL,
	[OrderNum_FreightTerms_c] [nvarchar](max) NULL,
	[OrderNum_ThirdParty_c] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OrderRel_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[ApplyChrg] [bit] NULL,
	[BuyToOrder] [bit] NULL,
	[ChangeDate] [date] NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [int] NULL,
	[ChrgAmount] [decimal](17, 3) NULL,
	[COD] [bit] NULL,
	[CODAmount] [decimal](17, 3) NULL,
	[CODCheck] [bit] NULL,
	[CODFreight] [bit] NULL,
	[Company] [nvarchar](max) NULL,
	[ComplianceMsg] [nvarchar](max) NULL,
	[DeclaredAmt] [decimal](17, 3) NULL,
	[DeclaredIns] [bit] NULL,
	[DeliveryType] [nvarchar](max) NULL,
	[DemandReference] [nvarchar](max) NULL,
	[DockingStation] [nvarchar](max) NULL,
	[DocOnly] [bit] NULL,
	[DropShip] [bit] NULL,
	[DropShipName] [nvarchar](max) NULL,
	[ECCPlant] [nvarchar](max) NULL,
	[GetDfltTaxIds] [bit] NULL,
	[GroundType] [nvarchar](max) NULL,
	[Hazmat] [bit] NULL,
	[IUM] [nvarchar](max) NULL,
	[LineType] [nvarchar](max) NULL,
	[Location] [nvarchar](max) NULL,
	[MarkForNum] [nvarchar](max) NULL,
	[MFCustNum] [int] NULL,
	[NeedByDate] [date] NULL,
	[NotifyEMail] [nvarchar](max) NULL,
	[NotifyFlag] [bit] NULL,
	[OpenOrder] [bit] NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[OrderRelNum] [int] NULL,
	[OTMFAddress1] [nvarchar](max) NULL,
	[OTMFAddress2] [nvarchar](max) NULL,
	[OTMFAddress3] [nvarchar](max) NULL,
	[OTMFCity] [nvarchar](max) NULL,
	[OTMFContact] [nvarchar](max) NULL,
	[OTMFCountryNum] [int] NULL,
	[OTMFFaxNum] [nvarchar](max) NULL,
	[OTMFName] [nvarchar](max) NULL,
	[OTMFPhoneNum] [nvarchar](max) NULL,
	[OTMFState] [nvarchar](max) NULL,
	[OTMFZIP] [nvarchar](max) NULL,
	[OTSAddress1] [nvarchar](max) NULL,
	[OTSAddress2] [nvarchar](max) NULL,
	[OTSAddress3] [nvarchar](max) NULL,
	[OTSCity] [nvarchar](max) NULL,
	[OTSContact] [nvarchar](max) NULL,
	[OTSCountryNum] [int] NULL,
	[OTSCustSaved] [bit] NULL,
	[OTSFaxNum] [nvarchar](max) NULL,
	[OTSName] [nvarchar](max) NULL,
	[OTSPhoneNum] [nvarchar](max) NULL,
	[OTSResaleID] [nvarchar](max) NULL,
	[OTSSaveAs] [nvarchar](max) NULL,
	[OTSSaveCustID] [nvarchar](max) NULL,
	[OTSState] [nvarchar](max) NULL,
	[OTSZIP] [nvarchar](max) NULL,
	[OverrideCarrier] [bit] NULL,
	[OverrideService] [bit] NULL,
	[PartNum] [nvarchar](max) NULL,
	[Plant] [nvarchar](max) NULL,
	[POLine] [int] NULL,
	[PONum] [int] NULL,
	[PORelNum] [int] NULL,
	[PrevNeedByDate] [date] NULL,
	[PrevPartNum] [nvarchar](max) NULL,
	[PrevReqDate] [date] NULL,
	[PrevSellQty] [decimal](12, 2) NULL,
	[PrevShipToNum] [nvarchar](max) NULL,
	[PrevXPartNum] [nvarchar](max) NULL,
	[PurPoint] [nvarchar](max) NULL,
	[RAN] [nvarchar](max) NULL,
	[Reference] [nvarchar](max) NULL,
	[RefNotes] [nvarchar](max) NULL,
	[RelStatus] [nvarchar](max) NULL,
	[ReqDate] [date] NULL,
	[ResDelivery] [bit] NULL,
	[RevisionNum] [nvarchar](max) NULL,
	[SalesUM] [nvarchar](max) NULL,
	[SatDelivery] [bit] NULL,
	[SatPickup] [bit] NULL,
	[ScheduleNumber] [nvarchar](max) NULL,
	[SellingReqQty] [decimal](22, 8) NULL,
	[ServAlert] [bit] NULL,
	[ServAOD] [bit] NULL,
	[ServAuthNum] [nvarchar](max) NULL,
	[ServDeliveryDate] [date] NULL,
	[ServHomeDel] [bit] NULL,
	[ServInstruct] [nvarchar](max) NULL,
	[ServPhone] [nvarchar](max) NULL,
	[ServPOD] [bit] NULL,
	[ServRelease] [bit] NULL,
	[ServSatDelivery] [bit] NULL,
	[ServSatPickup] [bit] NULL,
	[ServSignature] [bit] NULL,
	[ShipbyTime] [int] NULL,
	[ShipOvers] [bit] NULL,
	[ShipRouting] [nvarchar](max) NULL,
	[ShipToCustNum] [int] NULL,
	[ShipViaCode] [nvarchar](max) NULL,
	[ShpConNum] [int] NULL,
	[SubShipTo] [nvarchar](max) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[TaxConnectCalc] [bit] NULL,
	[TaxExempt] [nvarchar](max) NULL,
	[TaxRegionCode] [nvarchar](max) NULL,
	[TransportID] [nvarchar](max) NULL,
	[UseOTMF] [bit] NULL,
	[UseOTS] [bit] NULL,
	[VendorNum] [int] NULL,
	[VerbalConf] [bit] NULL,
	[WebSKU] [nvarchar](max) NULL,
	[WIItemPrice] [decimal](14, 5) NULL,
	[WIItemShipCost] [decimal](14, 5) NULL,
	[WIOrder] [nvarchar](max) NULL,
	[WIOrderLine] [nvarchar](max) NULL,
	[DropShip_Override_c] [bit] NULL,
	[PONum_Override_c] [int] NULL,
	[Calc_PrevNeedByDate] [datetime] NULL,
	[Calc_PrevReqDate] [datetime] NULL,
	[Calc_PrevSellReqQty] [decimal](38, 9) NULL,
	[Calc_PrevShipToNum] [nvarchar](max) NULL,
	[Calc_ResaleID] [nvarchar](max) NULL,
	[Calc_ShipToAddressList] [nvarchar](max) NULL,
	[Calc_ShipToContact] [nvarchar](max) NULL,
	[Calc_TaxCodes] [nvarchar](max) NULL,
	[OrderNum_CardMemberName] [nvarchar](max) NULL,
	[OrderNum_CurrencyCode] [nvarchar](max) NULL,
	[OrderNum_CheckBox01_c] [bit] NULL,
	[OrderNum_FreightTerms_c] [nvarchar](max) NULL,
	[OrderNum_ThirdParty_c] [nvarchar](max) NULL,
	[PartNum_MfgComment] [nvarchar](max) NULL,
	[PartNum_PartDescription] [nvarchar](max) NULL,
	[PartNum_PurComment] [nvarchar](max) NULL,
	[PartNum_TrackDimension] [bit] NULL,
	[PartNum_TrackLots] [bit] NULL,
	[PartNum_TrackSerialNum] [bit] NULL,
	[PartNum_Bare_c] [nvarchar](max) NULL,
	[PartNum_CartonWeight_c] [decimal](38, 9) NULL,
	[PartNum_CartperPallet_c] [decimal](38, 9) NULL,
	[PartNum_Commission_c] [nvarchar](max) NULL,
	[PartNum_CommissionExpire_c] [datetime] NULL,
	[PartNum_CreateUser_c] [nvarchar](max) NULL,
	[PartNum_DrawingNumber_c] [nvarchar](max) NULL,
	[PartNum_Excess_c] [bit] NULL,
	[PartNum_ExpireDate_c] [datetime] NULL,
	[PartNum_FreightClass_c] [nvarchar](max) NULL,
	[PartNum_Inspect_c] [bit] NULL,
	[PartNum_InventoryAgreement_c] [bit] NULL,
	[PartNum_Lifo_c] [decimal](38, 9) NULL,
	[PartNum_ManageApprove_c] [bit] NULL,
	[PartNum_MplsSS_c] [decimal](38, 9) NULL,
	[PartNum_NMFC_Code_c] [nvarchar](max) NULL,
	[PartNum_OpenStock_c] [bit] NULL,
	[PartNum_Pack_c] [decimal](38, 9) NULL,
	[PartNum_PcsPerPallet_c] [int] NULL,
	[PartNum_PrimaryComponent_c] [bit] NULL,
	[PartNum_VendItem_c] [nvarchar](max) NULL,
	[Plant_Name] [nvarchar](max) NULL,
	[ShipViaCode_Description] [nvarchar](max) NULL,
	[ShipViaCode_WebDesc] [nvarchar](max) NULL,
	[ShipViaCode_ServiceCode_c] [nvarchar](max) NULL,
	[WarehouseCode_Description] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[OrdRelTax_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[CurrencyCode] [nvarchar](max) NULL,
	[Discount] [decimal](38, 10) NULL,
	[DocDiscount] [decimal](38, 10) NULL,
	[DocReportableAmt] [decimal](38, 10) NULL,
	[DocTaxableAmt] [decimal](38, 10) NULL,
	[DocTaxAmt] [decimal](38, 10) NULL,
	[OrderLine] [int] NULL,
	[OrderNum] [int] NULL,
	[OrderRelNum] [int] NULL,
	[Percent] [decimal](38, 10) NULL,
	[ReportableAmt] [decimal](38, 10) NULL,
	[TaxableAmt] [decimal](38, 10) NULL,
	[TaxAmt] [decimal](38, 10) NULL,
	[TaxCode] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptLabels_1_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[DecimalsGeneral] [nvarchar](max) NULL,
	[DecimalsPrice] [nvarchar](max) NULL,
	[DecimalsCost] [nvarchar](max) NULL,
	[GlbDecimalsGeneral] [nvarchar](max) NULL,
	[GlbDecimalsPrice] [nvarchar](max) NULL,
	[GlbDecimalsCost] [nvarchar](max) NULL,
	[RptLiteralsPage] [nvarchar](max) NULL,
	[RptLiteralsTime] [nvarchar](max) NULL,
	[RptLiteralsUser] [nvarchar](max) NULL,
	[RptLiteralsDate] [nvarchar](max) NULL,
	[RptLiteralsComponentPrice] [nvarchar](max) NULL,
	[RptLiteralsCompPrice] [nvarchar](max) NULL,
	[RptLiteralsDiscount] [nvarchar](max) NULL,
	[RptLiteralsLBLQT] [nvarchar](max) NULL,
	[RptLiteralsLCarrier] [nvarchar](max) NULL,
	[RptLiteralsLCarrierSCAC] [nvarchar](max) NULL,
	[RptLiteralsLComp] [nvarchar](max) NULL,
	[RptLiteralsLComponents] [nvarchar](max) NULL,
	[RptLiteralsLCont] [nvarchar](max) NULL,
	[RptLiteralsLCrdNum] [nvarchar](max) NULL,
	[RptLiteralsLCustPart] [nvarchar](max) NULL,
	[RptLiteralsLDate] [nvarchar](max) NULL,
	[RptLiteralsLEmail] [nvarchar](max) NULL,
	[RptLiteralsLFax] [nvarchar](max) NULL,
	[RptLiteralsLKit] [nvarchar](max) NULL,
	[RptLiteralsLKitComponents] [nvarchar](max) NULL,
	[RptLiteralsLKitHeading] [nvarchar](max) NULL,
	[RptLiteralsLKits] [nvarchar](max) NULL,
	[RptLiteralsLKitSeq] [nvarchar](max) NULL,
	[RptLiteralsLLine] [nvarchar](max) NULL,
	[RptLiteralsLLNMSC] [nvarchar](max) NULL,
	[RptLiteralsLMSCTot] [nvarchar](max) NULL,
	[RptLiteralsLOrderAck] [nvarchar](max) NULL,
	[RptLiteralsLOrderLine] [nvarchar](max) NULL,
	[RptLiteralsLOrderLn] [nvarchar](max) NULL,
	[RptLiteralsLOrdQty] [nvarchar](max) NULL,
	[RptLiteralsLORMSC] [nvarchar](max) NULL,
	[RptLiteralsLORNUM] [nvarchar](max) NULL,
	[RptLiteralsLOurPart] [nvarchar](max) NULL,
	[RptLiteralsLPage] [nvarchar](max) NULL,
	[RptLiteralsLParent] [nvarchar](max) NULL,
	[RptLiteralsLPhone] [nvarchar](max) NULL,
	[RptLiteralsLPONum] [nvarchar](max) NULL,
	[RptLiteralsLPriPer] [nvarchar](max) NULL,
	[RptLiteralsLPrtDes] [nvarchar](max) NULL,
	[RptLiteralsLQPParent] [nvarchar](max) NULL,
	[RptLiteralsLQty] [nvarchar](max) NULL,
	[RptLiteralsLQtyPer] [nvarchar](max) NULL,
	[RptLiteralsLRounding] [nvarchar](max) NULL,
	[RptLiteralsLShipTo] [nvarchar](max) NULL,
	[RptLiteralsLSHSHC] [nvarchar](max) NULL,
	[RptLiteralsLSHSHM] [nvarchar](max) NULL,
	[RptLiteralsLSLSHE] [nvarchar](max) NULL,
	[RptLiteralsLSoldTo] [nvarchar](max) NULL,
	[RptLiteralsLSubTotal] [nvarchar](max) NULL,
	[RptLiteralsLTerms] [nvarchar](max) NULL,
	[RptLiteralsLYURPOLN] [nvarchar](max) NULL,
	[RptLiteralsSalesKit] [nvarchar](max) NULL,
	[RptLiteralsSeeBelow] [nvarchar](max) NULL,
	[AcctRefNumber] [nvarchar](max) NULL,
	[AcrossNatAcc] [nvarchar](max) NULL,
	[AddlHdlgFlag] [nvarchar](max) NULL,
	[Address1] [nvarchar](max) NULL,
	[Address2] [nvarchar](max) NULL,
	[Address3] [nvarchar](max) NULL,
	[AddressVal] [nvarchar](max) NULL,
	[AEPLOQType] [nvarchar](max) NULL,
	[AGAFIPResponsibilityCode] [nvarchar](max) NULL,
	[AGBillToProvinceCode] [nvarchar](max) NULL,
	[AGGrossIncomeTaxID] [nvarchar](max) NULL,
	[AGIDDocTypeCode] [nvarchar](max) NULL,
	[AGIDDocumentNumber] [nvarchar](max) NULL,
	[AGProvinceCode] [nvarchar](max) NULL,
	[AGUseGoodDefaultMark] [nvarchar](max) NULL,
	[AllocPriorityCode] [nvarchar](max) NULL,
	[AllowAltBillTo] [nvarchar](max) NULL,
	[AllowAsAltRemitTo] [nvarchar](max) NULL,
	[AllowOTS] [nvarchar](max) NULL,
	[AllowShipTo3] [nvarchar](max) NULL,
	[ApplyChrg] [nvarchar](max) NULL,
	[ARInvoiceAdjITCode] [nvarchar](max) NULL,
	[ARInvoiceITCode] [nvarchar](max) NULL,
	[BillDay] [nvarchar](max) NULL,
	[BillFrequency] [nvarchar](max) NULL,
	[BorderCrossing] [nvarchar](max) NULL,
	[BTAddress1] [nvarchar](max) NULL,
	[BTAddress2] [nvarchar](max) NULL,
	[BTAddress3] [nvarchar](max) NULL,
	[BTCity] [nvarchar](max) NULL,
	[BTCountry] [nvarchar](max) NULL,
	[BTCountryNum] [nvarchar](max) NULL,
	[BTFaxNum] [nvarchar](max) NULL,
	[BTFormatStr] [nvarchar](max) NULL,
	[BTName] [nvarchar](max) NULL,
	[BTPhoneNum] [nvarchar](max) NULL,
	[BTState] [nvarchar](max) NULL,
	[BTZip] [nvarchar](max) NULL,
	[BusinessCust] [nvarchar](max) NULL,
	[CertOfOrigin] [nvarchar](max) NULL,
	[ChangeDate] [nvarchar](max) NULL,
	[ChangedBy] [nvarchar](max) NULL,
	[ChangeTime] [nvarchar](max) NULL,
	[ChargeCode] [nvarchar](max) NULL,
	[CheckConfirmCapPromise] [nvarchar](max) NULL,
	[CheckDateCapPromise] [nvarchar](max) NULL,
	[CheckDuplicatePO] [nvarchar](max) NULL,
	[CheckUpdateCapPromise] [nvarchar](max) NULL,
	[ChrgAmount] [nvarchar](max) NULL,
	[City] [nvarchar](max) NULL,
	[COD] [nvarchar](max) NULL,
	[CODAmount] [nvarchar](max) NULL,
	[CODCheck] [nvarchar](max) NULL,
	[CODFreight] [nvarchar](max) NULL,
	[Comment] [nvarchar](max) NULL,
	[CommercialInvoice] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[ConsolidateSO] [nvarchar](max) NULL,
	[ContBillDay] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
	[CountryNum] [nvarchar](max) NULL,
	[CreditCardOrder] [nvarchar](max) NULL,
	[CreditClearDate] [nvarchar](max) NULL,
	[CreditClearTime] [nvarchar](max) NULL,
	[CreditClearUserID] [nvarchar](max) NULL,
	[CreditHold] [nvarchar](max) NULL,
	[CreditHoldDate] [nvarchar](max) NULL,
	[CreditHoldSource] [nvarchar](max) NULL,
	[CreditIncludeOrders] [nvarchar](max) NULL,
	[CreditIncludePI] [nvarchar](max) NULL,
	[CreditLimit] [nvarchar](max) NULL,
	[CreditMemoITCode] [nvarchar](max) NULL,
	[CreditReviewDate] [nvarchar](max) NULL,
	[CSR] [nvarchar](max) NULL,
	[CurrencyCode] [nvarchar](max) NULL,
	[CustID] [nvarchar](max) NULL,
	[CustNum] [nvarchar](max) NULL,
	[CustomerType] [nvarchar](max) NULL,
	[CustPartOpts] [nvarchar](max) NULL,
	[CustPILimit] [nvarchar](max) NULL,
	[CustPricingSchema] [nvarchar](max) NULL,
	[CustURL] [nvarchar](max) NULL,
	[DeclaredAmt] [nvarchar](max) NULL,
	[DeclaredIns] [nvarchar](max) NULL,
	[DefaultFOB] [nvarchar](max) NULL,
	[DefaultInvoicestyle] [nvarchar](max) NULL,
	[DefaultLOQstyle] [nvarchar](max) NULL,
	[DefaultOrderAcknowledgement] [nvarchar](max) NULL,
	[DefaultOversPricing] [nvarchar](max) NULL,
	[DefaultPackSlip] [nvarchar](max) NULL,
	[DeferredRev] [nvarchar](max) NULL,
	[DeliveryConf] [nvarchar](max) NULL,
	[DeliveryType] [nvarchar](max) NULL,
	[DemandAddAction] [nvarchar](max) NULL,
	[DemandAddLeadTime] [nvarchar](max) NULL,
	[DemandCancelAction] [nvarchar](max) NULL,
	[DemandCancelLeadTime] [nvarchar](max) NULL,
	[DemandCapPromiseAction] [nvarchar](max) NULL,
	[DemandCapPromiseDate] [nvarchar](max) NULL,
	[DemandCapPromiseUpdate] [nvarchar](max) NULL,
	[DemandChangeAction] [nvarchar](max) NULL,
	[DemandChangeDateAction] [nvarchar](max) NULL,
	[DemandChangeDateLeadTime] [nvarchar](max) NULL,
	[DemandChangeLeadTime] [nvarchar](max) NULL,
	[DemandCheckCfgAction] [nvarchar](max) NULL,
	[DemandCheckConfig] [nvarchar](max) NULL,
	[DemandCheckCUMM] [nvarchar](max) NULL,
	[DemandCheckCUMMAction] [nvarchar](max) NULL,
	[DemandCheckForPart] [nvarchar](max) NULL,
	[DemandCheckForPartAction] [nvarchar](max) NULL,
	[DemandCheckForRev] [nvarchar](max) NULL,
	[DemandCheckForRevAction] [nvarchar](max) NULL,
	[DemandCloseNoMatch] [nvarchar](max) NULL,
	[DemandCloseRejSkd] [nvarchar](max) NULL,
	[DemandDateType] [nvarchar](max) NULL,
	[DemandDeliveryDays] [nvarchar](max) NULL,
	[DemandNewLineAction] [nvarchar](max) NULL,
	[DemandNewLineLeadTime] [nvarchar](max) NULL,
	[DemandPricing] [nvarchar](max) NULL,
	[DemandQtyChangeAction] [nvarchar](max) NULL,
	[DemandQtyChangeLeadTime] [nvarchar](max) NULL,
	[DemandSplitSched] [nvarchar](max) NULL,
	[DemandUnitPriceDiff] [nvarchar](max) NULL,
	[DemandUnitPriceDiffAction] [nvarchar](max) NULL,
	[DirectDebiting] [nvarchar](max) NULL,
	[DiscountPercent] [nvarchar](max) NULL,
	[DiscountQualifier] [nvarchar](max) NULL,
	[DmdCheckPartialShip] [nvarchar](max) NULL,
	[DmdCheckShipAction] [nvarchar](max) NULL,
	[DocGlobalCreditLimit] [nvarchar](max) NULL,
	[DocGlobalPILimit] [nvarchar](max) NULL,
	[DocOnly] [nvarchar](max) NULL,
	[DueDateCriteria] [nvarchar](max) NULL,
	[EarlyBuffer] [nvarchar](max) NULL,
	[EDICode] [nvarchar](max) NULL,
	[EMailAddress] [nvarchar](max) NULL,
	[ERSOrder] [nvarchar](max) NULL,
	[EstDate] [nvarchar](max) NULL,
	[ETCAddrChg] [nvarchar](max) NULL,
	[ExcFromVal] [nvarchar](max) NULL,
	[ExternalDeliveryNote] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptLabels_2_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[ExternalID] [nvarchar](max) NULL,
	[ExtID] [nvarchar](max) NULL,
	[FaxNum] [nvarchar](max) NULL,
	[FederalID] [nvarchar](max) NULL,
	[FFAddress1] [nvarchar](max) NULL,
	[FFAddress2] [nvarchar](max) NULL,
	[FFAddress3] [nvarchar](max) NULL,
	[FFCity] [nvarchar](max) NULL,
	[FFCompName] [nvarchar](max) NULL,
	[FFContact] [nvarchar](max) NULL,
	[FFCountry] [nvarchar](max) NULL,
	[FFCountryNum] [nvarchar](max) NULL,
	[FFID] [nvarchar](max) NULL,
	[FFPhoneNum] [nvarchar](max) NULL,
	[FFState] [nvarchar](max) NULL,
	[FFZip] [nvarchar](max) NULL,
	[FinCharges] [nvarchar](max) NULL,
	[FormatStr] [nvarchar](max) NULL,
	[GlbNACreditIsShare] [nvarchar](max) NULL,
	[GlbNACreditSharedPrc] [nvarchar](max) NULL,
	[GlbNAParentCreditIsUsed] [nvarchar](max) NULL,
	[GlbNAParentCreditPrc] [nvarchar](max) NULL,
	[GlobalCredIncOrd] [nvarchar](max) NULL,
	[GlobalCredIncPI] [nvarchar](max) NULL,
	[GlobalCreditHold] [nvarchar](max) NULL,
	[GlobalCreditLimit] [nvarchar](max) NULL,
	[GlobalCurrencyCode] [nvarchar](max) NULL,
	[GlobalCust] [nvarchar](max) NULL,
	[GlobalLock] [nvarchar](max) NULL,
	[GlobalPILimit] [nvarchar](max) NULL,
	[GroundType] [nvarchar](max) NULL,
	[GroupCode] [nvarchar](max) NULL,
	[HasBank] [nvarchar](max) NULL,
	[Hazmat] [nvarchar](max) NULL,
	[ICCust] [nvarchar](max) NULL,
	[ICTrader] [nvarchar](max) NULL,
	[IndividualPackIDs] [nvarchar](max) NULL,
	[IntrntlShip] [nvarchar](max) NULL,
	[InvPerPackLine] [nvarchar](max) NULL,
	[LangNameID] [nvarchar](max) NULL,
	[LateBuffer] [nvarchar](max) NULL,
	[LegalName] [nvarchar](max) NULL,
	[LetterOfInstr] [nvarchar](max) NULL,
	[LinkPortNum] [nvarchar](max) NULL,
	[LOQBookCaFinishing] [nvarchar](max) NULL,
	[LOQBookCapaper] [nvarchar](max) NULL,
	[LOQBookCaPress] [nvarchar](max) NULL,
	[LOQBookCatPlates] [nvarchar](max) NULL,
	[LOQBookPCFinishing] [nvarchar](max) NULL,
	[LOQBookPCPaper] [nvarchar](max) NULL,
	[LOQBookPCPlates] [nvarchar](max) NULL,
	[LOQBookPCPress] [nvarchar](max) NULL,
	[LOQPrepressStyle] [nvarchar](max) NULL,
	[LOQVariations] [nvarchar](max) NULL,
	[ManagedVendID] [nvarchar](max) NULL,
	[ManagedVendNum] [nvarchar](max) NULL,
	[MarkUpID] [nvarchar](max) NULL,
	[MiscCashRecITCode] [nvarchar](max) NULL,
	[NACreditIsShare] [nvarchar](max) NULL,
	[NACreditPreferenceList] [nvarchar](max) NULL,
	[NACreditSharedPrc] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[NAParentCreditIsUsed] [nvarchar](max) NULL,
	[NAParentCreditPrc] [nvarchar](max) NULL,
	[NARlsClassCode] [nvarchar](max) NULL,
	[NoContact] [nvarchar](max) NULL,
	[NonStdPkg] [nvarchar](max) NULL,
	[NotifyEMail] [nvarchar](max) NULL,
	[NotifyFlag] [nvarchar](max) NULL,
	[OneInvPerPS] [nvarchar](max) NULL,
	[OrderHoldForReview] [nvarchar](max) NULL,
	[OrgRegCode] [nvarchar](max) NULL,
	[OTSmartString] [nvarchar](max) NULL,
	[OTSSaveAs] [nvarchar](max) NULL,
	[OurBankCode] [nvarchar](max) NULL,
	[OverrideRlsClass] [nvarchar](max) NULL,
	[OversPct] [nvarchar](max) NULL,
	[ParamCode] [nvarchar](max) NULL,
	[ParentCustNum] [nvarchar](max) NULL,
	[PBTerms] [nvarchar](max) NULL,
	[PendingTerritoryID] [nvarchar](max) NULL,
	[PeriodicBilling] [nvarchar](max) NULL,
	[PeriodicityCode] [nvarchar](max) NULL,
	[PhoneNum] [nvarchar](max) NULL,
	[PMUID] [nvarchar](max) NULL,
	[PreferredBank] [nvarchar](max) NULL,
	[PriceTolerance] [nvarchar](max) NULL,
	[PrimBCon] [nvarchar](max) NULL,
	[PrimPCon] [nvarchar](max) NULL,
	[PrimSCon] [nvarchar](max) NULL,
	[PrintAck] [nvarchar](max) NULL,
	[PrintLabels] [nvarchar](max) NULL,
	[PrintStatements] [nvarchar](max) NULL,
	[RACode] [nvarchar](max) NULL,
	[RebateForm] [nvarchar](max) NULL,
	[RebateVendorNum] [nvarchar](max) NULL,
	[RefNotes] [nvarchar](max) NULL,
	[ReminderCode] [nvarchar](max) NULL,
	[ResaleID] [nvarchar](max) NULL,
	[ResDelivery] [nvarchar](max) NULL,
	[ReservePriorityCode] [nvarchar](max) NULL,
	[RfqAttachAllow] [nvarchar](max) NULL,
	[SalesRepCode] [nvarchar](max) NULL,
	[SatDelivery] [nvarchar](max) NULL,
	[SatPickup] [nvarchar](max) NULL,
	[ServAlert] [nvarchar](max) NULL,
	[ServAuthNum] [nvarchar](max) NULL,
	[ServDeliveryDate] [nvarchar](max) NULL,
	[ServHomeDel] [nvarchar](max) NULL,
	[ServInstruct] [nvarchar](max) NULL,
	[ServPhone] [nvarchar](max) NULL,
	[ServRef1] [nvarchar](max) NULL,
	[ServRef2] [nvarchar](max) NULL,
	[ServRef3] [nvarchar](max) NULL,
	[ServRef4] [nvarchar](max) NULL,
	[ServRef5] [nvarchar](max) NULL,
	[ServRelease] [nvarchar](max) NULL,
	[ServSignature] [nvarchar](max) NULL,
	[ShipExprtDeclartn] [nvarchar](max) NULL,
	[ShippingQualifier] [nvarchar](max) NULL,
	[ShipToNum] [nvarchar](max) NULL,
	[ShipToTerrList] [nvarchar](max) NULL,
	[ShipViaCode] [nvarchar](max) NULL,
	[State] [nvarchar](max) NULL,
	[SysRevID] [nvarchar](max) NULL,
	[SysRowID] [nvarchar](max) NULL,
	[TaxAuthorityCode] [nvarchar](max) NULL,
	[TaxExempt] [nvarchar](max) NULL,
	[TaxMethod] [nvarchar](max) NULL,
	[TaxRegionCode] [nvarchar](max) NULL,
	[TaxRegReason] [nvarchar](max) NULL,
	[TaxRoundRule] [nvarchar](max) NULL,
	[TermsCode] [nvarchar](max) NULL,
	[TerritoryID] [nvarchar](max) NULL,
	[TerritoryLock] [nvarchar](max) NULL,
	[THBranchID] [nvarchar](max) NULL,
	[ThirdPLCust] [nvarchar](max) NULL,
	[TradingPartnerName] [nvarchar](max) NULL,
	[UndersPct] [nvarchar](max) NULL,
	[UPSQuantumView] [nvarchar](max) NULL,
	[UPSQVEmailType] [nvarchar](max) NULL,
	[UPSQVMemo] [nvarchar](max) NULL,
	[UPSQVShipFromName] [nvarchar](max) NULL,
	[ValidPayer] [nvarchar](max) NULL,
	[ValidShipTo] [nvarchar](max) NULL,
	[ValidSoldTo] [nvarchar](max) NULL,
	[Variations] [nvarchar](max) NULL,
	[WebCustomer] [nvarchar](max) NULL,
	[WIApplication] [nvarchar](max) NULL,
	[WICustomer] [nvarchar](max) NULL,
	[WIShippingCosts] [nvarchar](max) NULL,
	[Zip] [nvarchar](max) NULL,
	[CallLine] [nvarchar](max) NULL,
	[CallNum] [nvarchar](max) NULL,
	[DemandContractNum] [nvarchar](max) NULL,
	[DemandDtlSeq] [nvarchar](max) NULL,
	[DemandHeadSeq] [nvarchar](max) NULL,
	[DemandScheduleSeq] [nvarchar](max) NULL,
	[JobNum] [nvarchar](max) NULL,
	[OrderLine] [nvarchar](max) NULL,
	[OrderNum] [nvarchar](max) NULL,
	[OrderRelNum] [nvarchar](max) NULL,
	[PartNum] [nvarchar](max) NULL,
	[PlanID] [nvarchar](max) NULL,
	[Plant] [nvarchar](max) NULL,
	[PlanUserID] [nvarchar](max) NULL,
	[ProdQty] [nvarchar](max) NULL,
	[ReceivedQty] [nvarchar](max) NULL,
	[ShippedQty] [nvarchar](max) NULL,
	[TargetAssemblySeq] [nvarchar](max) NULL,
	[TargetJobNum] [nvarchar](max) NULL,
	[TargetMtlSeq] [nvarchar](max) NULL,
	[TFLineNum] [nvarchar](max) NULL,
	[WarehouseCode] [nvarchar](max) NULL,
	[WIPQty] [nvarchar](max) NULL,
	[CodeDesc] [nvarchar](max) NULL,
	[CodeID] [nvarchar](max) NULL,
	[CodeTypeID] [nvarchar](max) NULL,
	[CreateDate] [nvarchar](max) NULL,
	[CreateUser] [nvarchar](max) NULL,
	[GlobalUDCodes] [nvarchar](max) NULL,
	[IsActive] [nvarchar](max) NULL,
	[LongDesc] [nvarchar](max) NULL,
	[SystemFlag] [nvarchar](max) NULL,
	[AdvBAQRights] [nvarchar](max) NULL,
	[AllowMultipleSessions] [nvarchar](max) NULL,
	[AllowReq] [nvarchar](max) NULL,
	[AutoStartMonitor] [nvarchar](max) NULL,
	[BPMAdvancedUser] [nvarchar](max) NULL,
	[CanAccEpiEverywhere] [nvarchar](max) NULL,
	[CanAcessMobile] [nvarchar](max) NULL,
	[CanChangePassword] [nvarchar](max) NULL,
	[CanChangeSaveSettings] [nvarchar](max) NULL,
	[CanCustomize] [nvarchar](max) NULL,
	[CanDesignQSearch] [nvarchar](max) NULL,
	[CanEditCompAnnotations] [nvarchar](max) NULL,
	[CanEditHelpLinks] [nvarchar](max) NULL,
	[CanEditUserAnnotations] [nvarchar](max) NULL,
	[CanMaintainFavPrograms] [nvarchar](max) NULL,
	[CanMaintainFavQueries] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptLabels_3_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[CanMaintainFavURLs] [nvarchar](max) NULL,
	[CanMaintQuickSearch] [nvarchar](max) NULL,
	[CanOverrideAllocations] [nvarchar](max) NULL,
	[CanPersonalize] [nvarchar](max) NULL,
	[CanSuspend] [nvarchar](max) NULL,
	[CanTheme] [nvarchar](max) NULL,
	[CanTranslate] [nvarchar](max) NULL,
	[CanUseEntSearch] [nvarchar](max) NULL,
	[CompList] [nvarchar](max) NULL,
	[CurComp] [nvarchar](max) NULL,
	[CurFolderSeq] [nvarchar](max) NULL,
	[CurMenuID] [nvarchar](max) NULL,
	[DashboardDeveloper] [nvarchar](max) NULL,
	[DcdUserID] [nvarchar](max) NULL,
	[DispTips] [nvarchar](max) NULL,
	[DomainName] [nvarchar](max) NULL,
	[DspPayrollMgr] [nvarchar](max) NULL,
	[EntConType] [nvarchar](max) NULL,
	[EntSearchURL] [nvarchar](max) NULL,
	[FormatCulture] [nvarchar](max) NULL,
	[FormOpenMode] [nvarchar](max) NULL,
	[GlbCompSM] [nvarchar](max) NULL,
	[GroupList] [nvarchar](max) NULL,
	[JCDept] [nvarchar](max) NULL,
	[LastDate] [nvarchar](max) NULL,
	[LastGraphType] [nvarchar](max) NULL,
	[LastTime] [nvarchar](max) NULL,
	[ListViewMode] [nvarchar](max) NULL,
	[MaxGroupsFavorites] [nvarchar](max) NULL,
	[MaxGroupsSystemMenu] [nvarchar](max) NULL,
	[MobilePassword] [nvarchar](max) NULL,
	[MonitorPollingInterval] [nvarchar](max) NULL,
	[OfficePhone] [nvarchar](max) NULL,
	[OSUserID] [nvarchar](max) NULL,
	[PayrollMgr] [nvarchar](max) NULL,
	[Phone] [nvarchar](max) NULL,
	[PwdExpires] [nvarchar](max) NULL,
	[PwdExpiresDays] [nvarchar](max) NULL,
	[PwdGrace] [nvarchar](max) NULL,
	[PwdLastChanged] [nvarchar](max) NULL,
	[RequireSso] [nvarchar](max) NULL,
	[SaveSettings] [nvarchar](max) NULL,
	[SecurityAccessOnly] [nvarchar](max) NULL,
	[SecurityMgr] [nvarchar](max) NULL,
	[ShopTrackerReuseLast] [nvarchar](max) NULL,
	[ShpTrackerIntMinute] [nvarchar](max) NULL,
	[SolutionMgrCreate] [nvarchar](max) NULL,
	[SolutionMgrInstall] [nvarchar](max) NULL,
	[StartMenuClient] [nvarchar](max) NULL,
	[StartMenuEWA] [nvarchar](max) NULL,
	[StartMenuMobile] [nvarchar](max) NULL,
	[TEAprRetrieveApproved] [nvarchar](max) NULL,
	[TEAprRetrieveEntered] [nvarchar](max) NULL,
	[TEAprRetrievePartiallyApproved] [nvarchar](max) NULL,
	[TEAprRetrieveRejected] [nvarchar](max) NULL,
	[TEAprRetrieveSubmitted] [nvarchar](max) NULL,
	[TERetrieveApproved] [nvarchar](max) NULL,
	[TERetrieveEntered] [nvarchar](max) NULL,
	[TERetrievePartiallyApproved] [nvarchar](max) NULL,
	[TERetrieveRejected] [nvarchar](max) NULL,
	[TERetrieveSubmitted] [nvarchar](max) NULL,
	[Timeout] [nvarchar](max) NULL,
	[UseDefaultEntSearch] [nvarchar](max) NULL,
	[UseInternalWebBrowser] [nvarchar](max) NULL,
	[UserAccessOnly] [nvarchar](max) NULL,
	[UserDisabled] [nvarchar](max) NULL,
	[ViewFavoriteBar] [nvarchar](max) NULL,
	[ViewStatusBar] [nvarchar](max) NULL,
	[ViewStatusPanelCompany] [nvarchar](max) NULL,
	[ViewStatusPanelLanguage] [nvarchar](max) NULL,
	[ViewStatusPanelPlant] [nvarchar](max) NULL,
	[ViewStatusPanelServer] [nvarchar](max) NULL,
	[ViewStatusPanelUserID] [nvarchar](max) NULL,
	[ViewStatusPanelWorkstationID] [nvarchar](max) NULL,
	[ViewTreeOnly] [nvarchar](max) NULL,
	[WebUser] [nvarchar](max) NULL,
	[WinHeight] [nvarchar](max) NULL,
	[WinWidth] [nvarchar](max) NULL,
	[WinX] [nvarchar](max) NULL,
	[WinY] [nvarchar](max) NULL,
	[DeepCopy] [nvarchar](max) NULL,
	[DeepCopyDupOrRevEst] [nvarchar](max) NULL,
	[MapURL] [nvarchar](max) NULL,
	[WIAutoCreateJob] [nvarchar](max) NULL,
	[WIGetDetails] [nvarchar](max) NULL,
	[WIRelease] [nvarchar](max) NULL,
	[WISchedule] [nvarchar](max) NULL,
	[Calc_AddressList] [nvarchar](max) NULL,
	[Calc_PrintCompanyName] [nvarchar](max) NULL,
	[CardNumber] [nvarchar](max) NULL,
	[DocTotalDiscount] [nvarchar](max) NULL,
	[DocTotalMisc] [nvarchar](max) NULL,
	[DocTotalTax] [nvarchar](max) NULL,
	[ECCOrderNum] [nvarchar](max) NULL,
	[ECCPaymentMethod] [nvarchar](max) NULL,
	[ECCPONum] [nvarchar](max) NULL,
	[FOB] [nvarchar](max) NULL,
	[IsCSRSet] [nvarchar](max) NULL,
	[NeedByDate] [nvarchar](max) NULL,
	[OrderComment] [nvarchar](max) NULL,
	[OrderCSR] [nvarchar](max) NULL,
	[OrderDate] [nvarchar](max) NULL,
	[PONum] [nvarchar](max) NULL,
	[TotalMisc] [nvarchar](max) NULL,
	[TotalTax] [nvarchar](max) NULL,
	[TotalWHTax] [nvarchar](max) NULL,
	[WICreditCardorder] [nvarchar](max) NULL,
	[WIOrder] [nvarchar](max) NULL,
	[WIUserID] [nvarchar](max) NULL,
	[WIUsername] [nvarchar](max) NULL,
	[Calc_BillToAddressList] [nvarchar](max) NULL,
	[Calc_BillToContact] [nvarchar](max) NULL,
	[Calc_BTAddressList] [nvarchar](max) NULL,
	[Calc_CardNumber] [nvarchar](max) NULL,
	[Calc_CarrierDesc] [nvarchar](max) NULL,
	[Calc_CarrierSCAC] [nvarchar](max) NULL,
	[Calc_CustAddrList] [nvarchar](max) NULL,
	[Calc_CustPartOpts] [nvarchar](max) NULL,
	[Calc_FobDesc] [nvarchar](max) NULL,
	[Calc_MiscTotal] [nvarchar](max) NULL,
	[Calc_MultiNeedDate] [nvarchar](max) NULL,
	[Calc_MultiRef] [nvarchar](max) NULL,
	[Calc_MultiRel] [nvarchar](max) NULL,
	[Calc_MultiShipContacts] [nvarchar](max) NULL,
	[Calc_MultiShipTo] [nvarchar](max) NULL,
	[Calc_MultiShipVia] [nvarchar](max) NULL,
	[Calc_OrderTotal] [nvarchar](max) NULL,
	[Calc_PrcEmail] [nvarchar](max) NULL,
	[Calc_PrcFax] [nvarchar](max) NULL,
	[Calc_PrcPhone] [nvarchar](max) NULL,
	[Calc_RepRate] [nvarchar](max) NULL,
	[Calc_SalesPerson] [nvarchar](max) NULL,
	[Calc_ShipToAddressList] [nvarchar](max) NULL,
	[Calc_ShipToContact] [nvarchar](max) NULL,
	[Calc_ShipToEmail] [nvarchar](max) NULL,
	[Calc_ShipToFax] [nvarchar](max) NULL,
	[Calc_ShipToPhone] [nvarchar](max) NULL,
	[Calc_ShipViaDesc] [nvarchar](max) NULL,
	[Calc_SoldToBillToSameFlag] [nvarchar](max) NULL,
	[Calc_SubTotal] [nvarchar](max) NULL,
	[Calc_TermsDesc] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[CurrDesc] [nvarchar](max) NULL,
	[CurrName] [nvarchar](max) NULL,
	[CurrSymbol] [nvarchar](max) NULL,
	[DocumentDesc] [nvarchar](max) NULL,
	[WebDesc] [nvarchar](max) NULL,
	[ChangeTrackAmount] [nvarchar](max) NULL,
	[ChangeTrackApproved] [nvarchar](max) NULL,
	[ChangeTrackMemoDesc] [nvarchar](max) NULL,
	[ChangeTrackMemoText] [nvarchar](max) NULL,
	[ChangeTrackStatus] [nvarchar](max) NULL,
	[DocMiscAmt] [nvarchar](max) NULL,
	[FreqCode] [nvarchar](max) NULL,
	[MiscCode] [nvarchar](max) NULL,
	[SeqNum] [nvarchar](max) NULL,
	[Calc_ChargeDesc] [nvarchar](max) NULL,
	[Calc_SalesAnalysis] [nvarchar](max) NULL,
	[CardMemberName] [nvarchar](max) NULL,
	[ContractNum] [nvarchar](max) NULL,
	[DemandContractLine] [nvarchar](max) NULL,
	[DiscBreakListCode] [nvarchar](max) NULL,
	[DiscListPrice] [nvarchar](max) NULL,
	[DisplaySeq] [nvarchar](max) NULL,
	[DocDiscount] [nvarchar](max) NULL,
	[DocExtPriceDtl] [nvarchar](max) NULL,
	[DocInDiscount] [nvarchar](max) NULL,
	[DocInExtPriceDtl] [nvarchar](max) NULL,
	[DocInListPrice] [nvarchar](max) NULL,
	[DocInOrdBasedPrice] [nvarchar](max) NULL,
	[DocInUnitPrice] [nvarchar](max) NULL,
	[DocUnitPrice] [nvarchar](max) NULL,
	[DoNotShipAfterDate] [nvarchar](max) NULL,
	[DoNotShipBeforeDate] [nvarchar](max) NULL,
	[DupOnJobCrt] [nvarchar](max) NULL,
	[ECCOrderLine] [nvarchar](max) NULL,
	[ECCPlant] [nvarchar](max) NULL,
	[ECCQuoteLine] [nvarchar](max) NULL,
	[ECCQuoteNum] [nvarchar](max) NULL,
	[ExtPriceDtl] [nvarchar](max) NULL,
	[GroupSeq] [nvarchar](max) NULL,
	[InDiscount] [nvarchar](max) NULL,
	[InExtPriceDtl] [nvarchar](max) NULL,
	[InListPrice] [nvarchar](max) NULL,
	[InOrdBasedPrice] [nvarchar](max) NULL,
	[InUnitPrice] [nvarchar](max) NULL,
	[KitCompOrigPart] [nvarchar](max) NULL,
	[KitCompOrigSeq] [nvarchar](max) NULL,
	[KitFlag] [nvarchar](max) NULL,
	[KitParentLine] [nvarchar](max) NULL,
	[KitPricing] [nvarchar](max) NULL,
	[KitPrintCompsInv] [nvarchar](max) NULL,
	[KitPrintCompsPS] [nvarchar](max) NULL,
	[KitQtyPer] [nvarchar](max) NULL,
	[KitShipComplete] [nvarchar](max) NULL,
	[LineStatus] [nvarchar](max) NULL,
	[LockDisc] [nvarchar](max) NULL,
	[MOMsourceEst] [nvarchar](max) NULL,
	[MOMsourceType] [nvarchar](max) NULL,
	[OldOpenValue] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptLabels_4_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[OldOurOpenQty] [nvarchar](max) NULL,
	[OldProdCode] [nvarchar](max) NULL,
	[OldSellingOpenQty] [nvarchar](max) NULL,
	[OpenLine] [nvarchar](max) NULL,
	[OrderQty] [nvarchar](max) NULL,
	[OverrideDiscPriceList] [nvarchar](max) NULL,
	[Overs] [nvarchar](max) NULL,
	[OversUnitPrice] [nvarchar](max) NULL,
	[PlanGUID] [nvarchar](max) NULL,
	[POLine] [nvarchar](max) NULL,
	[PrevPartNum] [nvarchar](max) NULL,
	[PrevSellQty] [nvarchar](max) NULL,
	[PrevXPartNum] [nvarchar](max) NULL,
	[PricePerCode] [nvarchar](max) NULL,
	[Reference] [nvarchar](max) NULL,
	[RenewalNbr] [nvarchar](max) NULL,
	[ReverseCharge] [nvarchar](max) NULL,
	[RevisionNum] [nvarchar](max) NULL,
	[Rpt1AdvanceBillBal] [nvarchar](max) NULL,
	[Rpt1Discount] [nvarchar](max) NULL,
	[Rpt1ExtPriceDtl] [nvarchar](max) NULL,
	[Rpt1InDiscount] [nvarchar](max) NULL,
	[Rpt1InExtPriceDtl] [nvarchar](max) NULL,
	[Rpt1InListPrice] [nvarchar](max) NULL,
	[Rpt1InOrdBasedPrice] [nvarchar](max) NULL,
	[Rpt1InUnitPrice] [nvarchar](max) NULL,
	[Rpt1ListPrice] [nvarchar](max) NULL,
	[Rpt1OrdBasedPrice] [nvarchar](max) NULL,
	[Rpt1UnitPrice] [nvarchar](max) NULL,
	[Rpt2AdvanceBillBal] [nvarchar](max) NULL,
	[Rpt2Discount] [nvarchar](max) NULL,
	[Rpt2ExtPriceDtl] [nvarchar](max) NULL,
	[Rpt2InDiscount] [nvarchar](max) NULL,
	[Rpt2InExtPriceDtl] [nvarchar](max) NULL,
	[Rpt2InListPrice] [nvarchar](max) NULL,
	[Rpt2InOrdBasedPrice] [nvarchar](max) NULL,
	[Rpt2InUnitPrice] [nvarchar](max) NULL,
	[Rpt2ListPrice] [nvarchar](max) NULL,
	[Rpt2OrdBasedPrice] [nvarchar](max) NULL,
	[Rpt2UnitPrice] [nvarchar](max) NULL,
	[Rpt3AdvanceBillBal] [nvarchar](max) NULL,
	[Rpt3Discount] [nvarchar](max) NULL,
	[Rpt3ExtPriceDtl] [nvarchar](max) NULL,
	[Rpt3InDiscount] [nvarchar](max) NULL,
	[Rpt3InExtPriceDtl] [nvarchar](max) NULL,
	[Rpt3InListPrice] [nvarchar](max) NULL,
	[Rpt3InOrdBasedPrice] [nvarchar](max) NULL,
	[Rpt3InUnitPrice] [nvarchar](max) NULL,
	[Rpt3ListPrice] [nvarchar](max) NULL,
	[Rpt3OrdBasedPrice] [nvarchar](max) NULL,
	[Rpt3UnitPrice] [nvarchar](max) NULL,
	[SalesUM] [nvarchar](max) NULL,
	[SellingFactorDirection] [nvarchar](max) NULL,
	[SellingQuantity] [nvarchar](max) NULL,
	[SmartString] [nvarchar](max) NULL,
	[SmartStringProcessed] [nvarchar](max) NULL,
	[TotalReleases] [nvarchar](max) NULL,
	[Unders] [nvarchar](max) NULL,
	[UnitPrice] [nvarchar](max) NULL,
	[Warranty] [nvarchar](max) NULL,
	[WarrantyCode] [nvarchar](max) NULL,
	[WarrantyComment] [nvarchar](max) NULL,
	[XPartNum] [nvarchar](max) NULL,
	[XRevisionNum] [nvarchar](max) NULL,
	[Calc_Duration] [nvarchar](max) NULL,
	[Calc_ExtPrice] [nvarchar](max) NULL,
	[Calc_LabDur] [nvarchar](max) NULL,
	[Calc_LabMod] [nvarchar](max) NULL,
	[Calc_Labor] [nvarchar](max) NULL,
	[Calc_LineDesc] [nvarchar](max) NULL,
	[Calc_MatDur] [nvarchar](max) NULL,
	[Calc_Mate] [nvarchar](max) NULL,
	[Calc_MatMod] [nvarchar](max) NULL,
	[Calc_Misc] [nvarchar](max) NULL,
	[Calc_MiscDur] [nvarchar](max) NULL,
	[Calc_MiscMod] [nvarchar](max) NULL,
	[Calc_Modifier] [nvarchar](max) NULL,
	[Calc_POLine] [nvarchar](max) NULL,
	[Calc_PrevPartNum] [nvarchar](max) NULL,
	[Calc_PrevSellQty] [nvarchar](max) NULL,
	[Calc_PrevXPartNum] [nvarchar](max) NULL,
	[Calc_UOMForeignDesc] [nvarchar](max) NULL,
	[Calc_WarrComment] [nvarchar](max) NULL,
	[Calc_WarrDesc] [nvarchar](max) NULL,
	[ContractDescription] [nvarchar](max) NULL,
	[CampDescription] [nvarchar](max) NULL,
	[EvntDescription] [nvarchar](max) NULL,
	[MfgComment] [nvarchar](max) NULL,
	[PartDescription] [nvarchar](max) NULL,
	[PurComment] [nvarchar](max) NULL,
	[TrackDimension] [nvarchar](max) NULL,
	[TrackLots] [nvarchar](max) NULL,
	[TrackSerialNum] [nvarchar](max) NULL,
	[UOMSymbol] [nvarchar](max) NULL,
	[WarrDescription] [nvarchar](max) NULL,
	[DocInMiscAmt] [nvarchar](max) NULL,
	[ExtCompany] [nvarchar](max) NULL,
	[InMiscAmt] [nvarchar](max) NULL,
	[MiscAmt] [nvarchar](max) NULL,
	[Percentage] [nvarchar](max) NULL,
	[Rpt1InMiscAmt] [nvarchar](max) NULL,
	[Rpt1MiscAmt] [nvarchar](max) NULL,
	[Rpt2InMiscAmt] [nvarchar](max) NULL,
	[Rpt2MiscAmt] [nvarchar](max) NULL,
	[Rpt3InMiscAmt] [nvarchar](max) NULL,
	[Rpt3MiscAmt] [nvarchar](max) NULL,
	[Type] [nvarchar](max) NULL,
	[BuyToOrder] [nvarchar](max) NULL,
	[ComplianceMsg] [nvarchar](max) NULL,
	[DemandReference] [nvarchar](max) NULL,
	[DockingStation] [nvarchar](max) NULL,
	[DropShip] [nvarchar](max) NULL,
	[DropShipName] [nvarchar](max) NULL,
	[GetDfltTaxIds] [nvarchar](max) NULL,
	[IUM] [nvarchar](max) NULL,
	[LineType] [nvarchar](max) NULL,
	[Location] [nvarchar](max) NULL,
	[MarkForNum] [nvarchar](max) NULL,
	[MFCustNum] [nvarchar](max) NULL,
	[OpenOrder] [nvarchar](max) NULL,
	[OTMFAddress1] [nvarchar](max) NULL,
	[OTMFAddress2] [nvarchar](max) NULL,
	[OTMFAddress3] [nvarchar](max) NULL,
	[OTMFCity] [nvarchar](max) NULL,
	[OTMFContact] [nvarchar](max) NULL,
	[OTMFCountryNum] [nvarchar](max) NULL,
	[OTMFFaxNum] [nvarchar](max) NULL,
	[OTMFName] [nvarchar](max) NULL,
	[OTMFPhoneNum] [nvarchar](max) NULL,
	[OTMFState] [nvarchar](max) NULL,
	[OTMFZIP] [nvarchar](max) NULL,
	[OTSAddress1] [nvarchar](max) NULL,
	[OTSAddress2] [nvarchar](max) NULL,
	[OTSAddress3] [nvarchar](max) NULL,
	[OTSCity] [nvarchar](max) NULL,
	[OTSContact] [nvarchar](max) NULL,
	[OTSCountryNum] [nvarchar](max) NULL,
	[OTSCustSaved] [nvarchar](max) NULL,
	[OTSFaxNum] [nvarchar](max) NULL,
	[OTSName] [nvarchar](max) NULL,
	[OTSPhoneNum] [nvarchar](max) NULL,
	[OTSResaleID] [nvarchar](max) NULL,
	[OTSSaveCustID] [nvarchar](max) NULL,
	[OTSState] [nvarchar](max) NULL,
	[OTSZIP] [nvarchar](max) NULL,
	[OverrideCarrier] [nvarchar](max) NULL,
	[OverrideService] [nvarchar](max) NULL,
	[PORelNum] [nvarchar](max) NULL,
	[PrevNeedByDate] [nvarchar](max) NULL,
	[PrevReqDate] [nvarchar](max) NULL,
	[PrevShipToNum] [nvarchar](max) NULL,
	[PurPoint] [nvarchar](max) NULL,
	[RAN] [nvarchar](max) NULL,
	[RelStatus] [nvarchar](max) NULL,
	[ReqDate] [nvarchar](max) NULL,
	[ScheduleNumber] [nvarchar](max) NULL,
	[SellingReqQty] [nvarchar](max) NULL,
	[ServAOD] [nvarchar](max) NULL,
	[ServPOD] [nvarchar](max) NULL,
	[ServSatDelivery] [nvarchar](max) NULL,
	[ServSatPickup] [nvarchar](max) NULL,
	[ShipbyTime] [nvarchar](max) NULL,
	[ShipOvers] [nvarchar](max) NULL,
	[ShipRouting] [nvarchar](max) NULL,
	[ShipToCustNum] [nvarchar](max) NULL,
	[ShpConNum] [nvarchar](max) NULL,
	[SubShipTo] [nvarchar](max) NULL,
	[TaxConnectCalc] [nvarchar](max) NULL,
	[TransportID] [nvarchar](max) NULL,
	[UseOTMF] [nvarchar](max) NULL,
	[UseOTS] [nvarchar](max) NULL,
	[VendorNum] [nvarchar](max) NULL,
	[VerbalConf] [nvarchar](max) NULL,
	[WebSKU] [nvarchar](max) NULL,
	[WIItemPrice] [nvarchar](max) NULL,
	[WIItemShipCost] [nvarchar](max) NULL,
	[WIOrderLine] [nvarchar](max) NULL,
	[Calc_PrevNeedByDate] [nvarchar](max) NULL,
	[Calc_PrevReqDate] [nvarchar](max) NULL,
	[Calc_PrevSellReqQty] [nvarchar](max) NULL,
	[Calc_PrevShipToNum] [nvarchar](max) NULL,
	[Calc_ResaleID] [nvarchar](max) NULL,
	[Calc_TaxCodes] [nvarchar](max) NULL,
	[BillEndDate] [nvarchar](max) NULL,
	[BillStartDate] [nvarchar](max) NULL,
	[ContractLine] [nvarchar](max) NULL,
	[ContractQty] [nvarchar](max) NULL,
	[DateInactivated] [nvarchar](max) NULL,
	[DateInvoiced] [nvarchar](max) NULL,
	[DocPricePerUnit] [nvarchar](max) NULL,
	[Inactive] [nvarchar](max) NULL,
	[Invoiced] [nvarchar](max) NULL,
	[Rpt1PricePerUnit] [nvarchar](max) NULL,
	[Rpt2PricePerUnit] [nvarchar](max) NULL,
	[Rpt3PricePerUnit] [nvarchar](max) NULL,
	[Calc_OrderLine] [nvarchar](max) NULL,
	[Calc_OrderNum] [nvarchar](max) NULL,
	[Discount] [nvarchar](max) NULL,
	[DocReportableAmt] [nvarchar](max) NULL,
	[DocTaxableAmt] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptLabels_5_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[DocTaxAmt] [nvarchar](max) NULL,
	[Percent] [nvarchar](max) NULL,
	[ReportableAmt] [nvarchar](max) NULL,
	[TaxableAmt] [nvarchar](max) NULL,
	[TaxAmt] [nvarchar](max) NULL,
	[TaxCode] [nvarchar](max) NULL,
	[AcceptType] [nvarchar](max) NULL,
	[AltTradingPartnerName] [nvarchar](max) NULL,
	[DocDirection] [nvarchar](max) NULL,
	[DocumentName] [nvarchar](max) NULL,
	[DocumentType] [nvarchar](max) NULL,
	[EDIPartValidation] [nvarchar](max) NULL,
	[MapID] [nvarchar](max) NULL,
	[OutboundAutomatic] [nvarchar](max) NULL,
	[OutboundDocName] [nvarchar](max) NULL,
	[OutBoundDocReq] [nvarchar](max) NULL,
	[OutboundManual] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[RptParameter_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[Company] [nvarchar](max) NULL,
	[DCHdrList] [nvarchar](max) NULL,
	[OrderList] [nvarchar](max) NULL,
	[OrderNum] [int] NULL,
	[ReportCultureCode] [nvarchar](max) NULL,
	[ReportCurrencyCode] [nvarchar](max) NULL,
	[ThousandsSeparator] [nvarchar](max) NULL,
	[DecimalSeparator] [nvarchar](max) NULL,
	[DecimalsGeneral] [int] NULL,
	[DecimalsCost] [int] NULL,
	[DecimalsPrice] [int] NULL,
	[GlbDecimalsGeneral] [int] NULL,
	[GlbDecimalsCost] [int] NULL,
	[GlbDecimalsPrice] [int] NULL,
	[DecimalsQuantity] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[UDCodes_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[CodeDesc] [nvarchar](max) NULL,
	[CodeID] [nvarchar](max) NULL,
	[CodeTypeID] [nvarchar](max) NULL,
	[Company] [nvarchar](max) NULL,
	[CreateDate] [date] NULL,
	[CreateUser] [nvarchar](max) NULL,
	[GlobalLock] [bit] NULL,
	[GlobalUDCodes] [bit] NULL,
	[IsActive] [bit] NULL,
	[LongDesc] [nvarchar](max) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[SystemFlag] [bit] NULL,
	[Number01] [decimal](13, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[UserFile_DF3DAEF10B264D3B96EE58F0E6B8AC16](
	[RptLanguageID] [nvarchar](max) NULL,
	[Address1] [nvarchar](max) NULL,
	[Address2] [nvarchar](max) NULL,
	[AdvBAQRights] [bit] NULL,
	[AllowMultipleSessions] [bit] NULL,
	[AllowReq] [bit] NULL,
	[AutoStartMonitor] [bit] NULL,
	[BPMAdvancedUser] [bit] NULL,
	[CanAccEpiEverywhere] [bit] NULL,
	[CanAcessMobile] [bit] NULL,
	[CanChangePassword] [bit] NULL,
	[CanChangeSaveSettings] [bit] NULL,
	[CanCustomize] [bit] NULL,
	[CanDesignQSearch] [bit] NULL,
	[CanEditCompAnnotations] [bit] NULL,
	[CanEditHelpLinks] [nvarchar](max) NULL,
	[CanEditUserAnnotations] [bit] NULL,
	[CanMaintainFavPrograms] [bit] NULL,
	[CanMaintainFavQueries] [bit] NULL,
	[CanMaintainFavURLs] [bit] NULL,
	[CanMaintQuickSearch] [bit] NULL,
	[CanOverrideAllocations] [bit] NULL,
	[CanPersonalize] [bit] NULL,
	[CanSuspend] [bit] NULL,
	[CanTheme] [bit] NULL,
	[CanTranslate] [bit] NULL,
	[CanUseEntSearch] [bit] NULL,
	[City] [nvarchar](max) NULL,
	[CompList] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
	[CurComp] [nvarchar](max) NULL,
	[CurFolderSeq] [int] NULL,
	[CurMenuID] [nvarchar](max) NULL,
	[DashboardDeveloper] [bit] NULL,
	[DcdUserID] [nvarchar](max) NULL,
	[DispTips] [bit] NULL,
	[DomainName] [nvarchar](max) NULL,
	[DspPayrollMgr] [bit] NULL,
	[EMailAddress] [nvarchar](max) NULL,
	[EntConType] [nvarchar](max) NULL,
	[EntSearchURL] [nvarchar](max) NULL,
	[FormatCulture] [nvarchar](max) NULL,
	[FormOpenMode] [nvarchar](max) NULL,
	[GlbCompSM] [bit] NULL,
	[GroupList] [nvarchar](max) NULL,
	[JCDept] [nvarchar](max) NULL,
	[LangNameID] [nvarchar](max) NULL,
	[LastDate] [date] NULL,
	[LastGraphType] [nvarchar](max) NULL,
	[LastTime] [int] NULL,
	[ListViewMode] [int] NULL,
	[MaxGroupsFavorites] [int] NULL,
	[MaxGroupsSystemMenu] [int] NULL,
	[MobilePassword] [nvarchar](max) NULL,
	[MonitorPollingInterval] [int] NULL,
	[Name] [nvarchar](max) NULL,
	[OfficePhone] [nvarchar](max) NULL,
	[OSUserID] [nvarchar](max) NULL,
	[PayrollMgr] [nvarchar](max) NULL,
	[Phone] [nvarchar](max) NULL,
	[PwdExpires] [date] NULL,
	[PwdExpiresDays] [int] NULL,
	[PwdGrace] [int] NULL,
	[PwdLastChanged] [date] NULL,
	[RequireSso] [bit] NULL,
	[SaveSettings] [bit] NULL,
	[SecurityAccessOnly] [bit] NULL,
	[SecurityMgr] [bit] NULL,
	[ShopTrackerReuseLast] [nvarchar](max) NULL,
	[ShpTrackerIntMinute] [int] NULL,
	[SolutionMgrCreate] [bit] NULL,
	[SolutionMgrInstall] [bit] NULL,
	[StartMenuClient] [nvarchar](max) NULL,
	[StartMenuEWA] [nvarchar](max) NULL,
	[StartMenuMobile] [nvarchar](max) NULL,
	[State] [nvarchar](max) NULL,
	[SysRevID] [bigint] NULL,
	[SysRowID] [char](36) NULL,
	[TEAprRetrieveApproved] [bit] NULL,
	[TEAprRetrieveEntered] [bit] NULL,
	[TEAprRetrievePartiallyApproved] [bit] NULL,
	[TEAprRetrieveRejected] [bit] NULL,
	[TEAprRetrieveSubmitted] [bit] NULL,
	[TERetrieveApproved] [bit] NULL,
	[TERetrieveEntered] [bit] NULL,
	[TERetrievePartiallyApproved] [bit] NULL,
	[TERetrieveRejected] [bit] NULL,
	[TERetrieveSubmitted] [bit] NULL,
	[Timeout] [int] NULL,
	[UseDefaultEntSearch] [bit] NULL,
	[UseInternalWebBrowser] [bit] NULL,
	[UserAccessOnly] [bit] NULL,
	[UserDisabled] [bit] NULL,
	[ViewFavoriteBar] [bit] NULL,
	[ViewStatusBar] [bit] NULL,
	[ViewStatusPanelCompany] [bit] NULL,
	[ViewStatusPanelLanguage] [bit] NULL,
	[ViewStatusPanelPlant] [bit] NULL,
	[ViewStatusPanelServer] [bit] NULL,
	[ViewStatusPanelUserID] [bit] NULL,
	[ViewStatusPanelWorkstationID] [bit] NULL,
	[ViewTreeOnly] [int] NULL,
	[WebUser] [bit] NULL,
	[WinHeight] [int] NULL,
	[WinWidth] [int] NULL,
	[WinX] [int] NULL,
	[WinY] [int] NULL,
	[ZIP] [nvarchar](max) NULL,
	[Authorize_c] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



